"""
handsome_guys.py - 100 trai đẹp châu Á, xoay vòng theo ngày (day_of_year % len(GUYS))
Tiêu chí: cao từ 1m75 trở lên, thư sinh / idol / diễn viên
Fields: name, origin, job, birthday, height, weight, blood_type, zodiac,
        fav_color, fav_number, status, hobbies, top_works, awards, intro, image_url, tags
"""

GUYS = [
    # ── 🇻🇳 Việt Nam ─────────────────────────────────────────────────────────
    {
        "name": "Sơn Tùng M-TP",
        "origin": "Việt Nam 🇻🇳", "job": "Ca sĩ, producer",
        "birthday": "05/07/1994", "height": "1m75", "weight": "63 kg",
        "blood_type": "O", "zodiac": "Cự Giải ♋",
        "fav_color": "Đen & Trắng", "fav_number": "5",
        "status": "Đang hẹn hò 💑",
        "hobbies": "Sản xuất nhạc, thời trang, gym, sneaker collection",
        "top_works": "'Lạc Trôi', 'Có Chắc Yêu Là Đây', 'Making My Way', 'Hãy Trao Cho Anh'",
        "awards": "MTV EMA Đông Nam Á, Làn Sóng Xanh nhiều lần, VTV Awards",
        "intro": "Sơn Tùng M-TP sinh ngày 05/07/1994 từ Thái Bình — nghệ sĩ Việt Nam đầu tiên có MV đạt hàng trăm triệu view trên YouTube. Cao 1m75, style thời trang đỉnh, nhạc tự viết-tự produce-tự đạo diễn concept. 'Making My Way' phá kỷ lục streaming VN, 'Lạc Trôi' gây bão quốc tế.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/S%C6%A1n_T%C3%B9ng_M-TP_in_2019.jpg/440px-S%C6%A1n_T%C3%B9ng_M-TP_in_2019.jpg",
        "tags": ["V-pop", "producer", "icon"],
    },
    {
        "name": "SOOBIN Hoàng Sơn",
        "origin": "Việt Nam 🇻🇳", "job": "Ca sĩ, nhạc sĩ",
        "birthday": "07/01/1995", "height": "1m80", "weight": "70 kg",
        "blood_type": "B", "zodiac": "Ma Kết ♑",
        "fav_color": "Xanh navy", "fav_number": "7",
        "status": "Độc thân 💫",
        "hobbies": "Sản xuất nhạc, đọc thơ, yoga, cà phê",
        "top_works": "'Tội Ác', 'Em Của Ngày Hôm Qua', 'Muôn Kiếp Nhân Sinh', album 'SOOBIN'",
        "awards": "VTV Awards, Cống hiến Awards, MTV Vietnam",
        "intro": "SOOBIN sinh ngày 07/01/1995, cao 1m80 — gương mặt góc cạnh, phong thái điềm tĩnh đầy nội tâm. Album solo 'SOOBIN' được đánh giá là một trong những album Việt xuất sắc nhất thập kỷ. Người ta mê anh không chỉ vì visual mà còn vì chiều sâu nghệ thuật.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Choi_Soo-bin_%28%EC%B5%9C%EC%88%98%EB%B9%88%29_220121.jpg/400px-Choi_Soo-bin_%28%EC%B5%9C%EC%88%98%EB%B9%88%29_220121.jpg", "tags": ["V-pop", "nhạc sĩ", "indie"],
    },
    {
        "name": "Isaac (Jun Phạm)",
        "origin": "Việt Nam 🇻🇳", "job": "Ca sĩ, diễn viên",
        "birthday": "22/11/1994", "height": "1m79", "weight": "68 kg",
        "blood_type": "AB", "zodiac": "Bọ Cạp ♏",
        "fav_color": "Đen", "fav_number": "22",
        "status": "Độc thân 💫",
        "hobbies": "Gym, bơi lội, nấu ăn, du lịch",
        "top_works": "'Thằng Điên', 'Nồng Nàn Hơi Thở Em', phim 'Song Lang' (LHP Busan)",
        "awards": "Diễn viên xuất sắc LHP Busan, đề cử nhiều giải thưởng điện ảnh",
        "intro": "Isaac sinh ngày 22/11/1994, cao 1m79 — từ 365 đến solo career thành công vang dội. Vai diễn trong 'Song Lang' đoạt giải tại LHP Busan, đưa tên tuổi ra quốc tế. Ballad ngọt, diễn xuất chất, body gym đẹp — combo hoàn hảo.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Jun_Pham_GDHH.png/400px-Jun_Pham_GDHH.png", "tags": ["V-pop", "diễn viên", "ballad"],
    },
    {
        "name": "Đen Vâu",
        "origin": "Việt Nam 🇻🇳", "job": "Rapper, nhạc sĩ",
        "birthday": "16/12/1993", "height": "1m75", "weight": "65 kg",
        "blood_type": "A", "zodiac": "Nhân Mã ♐",
        "fav_color": "Nâu đất", "fav_number": "16",
        "status": "Đã kết hôn 💍",
        "hobbies": "Đọc sách, viết lời, chụp ảnh phim, cà phê sáng",
        "top_works": "'Mang Tiền Về Cho Mẹ', 'Bài Này Chill Phết', 'Đi Về Nhà', 'Anh Đếch Cần Gì Cả'",
        "awards": "Cống hiến Awards, VTV Awards, Ca sĩ của năm nhiều trang báo",
        "intro": "Đen Vâu sinh ngày 16/12/1993 — rapper Hà Nội với phong cách trữ tình độc nhất V-rap. Nhạc anh kể chuyện đời thường bằng ngôn từ tinh tế, chạm trái tim hàng triệu người. 'Mang Tiền Về Cho Mẹ' là bài anthem thế hệ không thể tranh cãi.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Den_Vau_in_Song_Gallery_2021.jpg", "tags": ["rapper", "V-rap", "indie"],
    },
    {
        "name": "Tăng Duy Tân",
        "origin": "Việt Nam 🇻🇳", "job": "Ca sĩ",
        "birthday": "17/03/1998", "height": "1m76", "weight": "65 kg",
        "blood_type": "O", "zodiac": "Song Ngư ♓",
        "fav_color": "Xanh lá Tây Nguyên", "fav_number": "8",
        "status": "Độc thân 💫",
        "hobbies": "Guitar, trekking, ẩm thực Tây Nguyên",
        "top_works": "'Không Thể Say', 'Tôi Thấy Hoa Vàng Trên Cỏ Xanh' OST, 'Lời Hứa Của Anh'",
        "awards": "Top trending nhạc Việt, hàng triệu stream Spotify",
        "intro": "Tăng Duy Tân sinh ngày 17/03/1998 — chàng trai Gia Lai với nụ cười rạng rỡ đặc trưng. 'Không Thể Say' viral khắp mạng xã hội, chứng minh âm nhạc dân gian đương đại có thể chinh phục thế hệ trẻ. Da ngăm khỏe khoắn, vibe miền cao tự nhiên.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Tangduytan.png", "tags": ["V-pop", "dân gian đương đại"],
    },
    {
        "name": "Noo Phước Thịnh",
        "origin": "Việt Nam 🇻🇳", "job": "Ca sĩ",
        "birthday": "02/11/1987", "height": "1m78", "weight": "68 kg",
        "blood_type": "O", "zodiac": "Bọ Cạp ♏",
        "fav_color": "Đỏ", "fav_number": "2",
        "status": "Độc thân 💫",
        "hobbies": "Nhảy (chuyên nghiệp), gym, trình diễn sân khấu",
        "top_works": "'Cause I Love You', 'Chạm Khẽ Tim Anh Một Chút Thôi', 'Tâm Sự Tuổi 30'",
        "awards": "Làn Sóng Xanh nhiều lần, VTV Awards, ông hoàng nhạc dance V-pop",
        "intro": "Noo Phước Thịnh sinh ngày 02/11/1987 — ông hoàng nhạc dance V-pop với vũ đạo điêu luyện đỉnh cao. Body từ tập nhảy chuyên nghiệp cân đối đẹp mắt. Hát live + nhảy cùng lúc cực chuẩn — tài năng hiếm gặp trong showbiz Việt.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/c/cf/Noo_Ph%C6%B0%E1%BB%9Bc_Th%E1%BB%8Bnh.png", "tags": ["V-pop", "dance", "icon"],
    },
    {
        "name": "Erik (Nguyễn Minh Anh)",
        "origin": "Việt Nam 🇻🇳", "job": "Ca sĩ",
        "birthday": "17/06/1997", "height": "1m77", "weight": "64 kg",
        "blood_type": "O", "zodiac": "Song Tử ♊",
        "fav_color": "Vàng", "fav_number": "17",
        "status": "Độc thân 💫",
        "hobbies": "Sáng tác nhạc, gym, dance cover, ăn vặt",
        "top_works": "'Ghen' (WHO sử dụng toàn cầu), 'Nơi Này Có Anh', 'Về Nghe Mẹ Ru'",
        "awards": "Top nhạc số VN, 'Ghen' được WHO dùng trong chiến dịch COVID-19",
        "intro": "Erik sinh ngày 17/06/1997 — khuôn mặt bầu bĩnh dễ thương, năng lượng dồi dào. 'Ghen' là ca khúc Việt Nam đầu tiên được WHO lấy làm nhạc nền chiến dịch phòng chống COVID-19 toàn cầu — cột mốc lịch sử! 'Nơi Này Có Anh' = bài tỏ tình được dùng nhiều nhất Việt Nam.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/83/Erik_t%E1%BA%A1i_s%E1%BB%B1_ki%E1%BB%87n%2C_2020-03-21.png", "tags": ["V-pop", "ca sĩ"],
    },
    {
        "name": "Rhyder (Trần Minh Tú)",
        "origin": "Việt Nam 🇻🇳", "job": "Ca sĩ, nhạc sĩ, producer",
        "birthday": "06/03/2000", "height": "1m78", "weight": "67 kg",
        "blood_type": "O", "zodiac": "Song Ngư ♓",
        "fav_color": "Xanh dương đậm", "fav_number": "6",
        "status": "Độc thân 💫",
        "hobbies": "Sản xuất nhạc, gym, đọc tâm lý học, chụp ảnh film",
        "top_works": "'Người Lạ Ơi' (collab Karik), 'Ngủ Một Mình', 'Làm Gì Đây'",
        "awards": "Top BXH nhạc Việt, hàng chục triệu stream, giới chuyên môn đánh giá cao",
        "intro": "Rhyder sinh ngày 06/03/2000 — hiện tượng V-pop với chất nhạc R&B-soul thuần túy hiếm gặp. Viết, sản xuất và hát đều đỉnh. 'Người Lạ Ơi' với Karik viral từ Bắc đến Nam. Style laid-back chill, khuôn mặt điền trai.",
        "image_url": "", "tags": ["V-pop", "R&B", "Gen Z"],
    },
    {
        "name": "Đinh Quốc Thiên",
        "origin": "Việt Nam 🇻🇳", "job": "Ca sĩ",
        "birthday": "10/11/1990", "height": "1m78", "weight": "67 kg",
        "blood_type": "A", "zodiac": "Bọ Cạp ♏",
        "fav_color": "Xanh lam", "fav_number": "10",
        "status": "Đã kết hôn 💍",
        "hobbies": "Guitar, thể dục, du lịch gia đình",
        "top_works": "'Tình Yêu Màu Nắng', Top 4 Giọng Hát Việt mùa 1, 'Anh Vẫn Đứng Đây'",
        "awards": "Top 4 Giọng Hát Việt, nhiều giải âm nhạc trong nước",
        "intro": "Đinh Quốc Thiên sinh ngày 10/11/1990, cao 1m78 — giọng hát trong trẻo, phong thái điềm tĩnh, nụ cười hiền lành đặc trưng. Top 4 Giọng Hát Việt mùa 1 đưa anh đến với khán giả cả nước. Ngoài đời là người chồng người cha tử tế — đủ để chị em thấy ấm lòng!",
        "image_url": "", "tags": ["V-pop", "ballad", "ca sĩ"],
    },
    {
        "name": "Anh Tú (Voi Bản Đôn)",
        "origin": "Việt Nam 🇻🇳", "job": "Ca sĩ, diễn viên hài",
        "birthday": "14/02/1993", "height": "1m77", "weight": "70 kg",
        "blood_type": "B", "zodiac": "Bảo Bình ♒",
        "fav_color": "Xanh lá", "fav_number": "14",
        "status": "Độc thân 💫",
        "hobbies": "Content hài hước, gym, chơi với voi (nghề truyền thống gia đình), du lịch bụi",
        "top_works": "'Anh Trai Say Hi' (gameshow viral 2024), nhiều clip hài triệu view",
        "awards": "Top trending MXH Việt Nam 2024, được yêu thích rộng rãi qua 'Anh Trai Say Hi'",
        "intro": "Anh Tú Voi Bản Đôn sinh ngày 14/02/1993 — độc nhất showbiz Việt: gia đình người Ê Đê có truyền thống thuần dưỡng voi tại Buôn Đôn! Tính cách hài hước tự nhiên, thân thiện không khách sáo. 'Anh Trai Say Hi' 2024 khiến anh bùng nổ trên toàn quốc.",
        "image_url": "", "tags": ["V-pop", "gameshow", "Tây Nguyên"],
    },
    {
        "name": "Jack (J97)",
        "origin": "Việt Nam 🇻🇳", "job": "Ca sĩ, rapper",
        "birthday": "05/01/1997", "height": "1m75", "weight": "62 kg",
        "blood_type": "A", "zodiac": "Ma Kết ♑",
        "fav_color": "Trắng", "fav_number": "5",
        "status": "Có con 👶",
        "hobbies": "Viết nhạc, xem phim, chơi với con",
        "top_works": "'Hoa Hải Đường', 'Bạc Phận', 'Muộn Rồi Mà Sao Còn', 'Sóng Gió'",
        "awards": "Top nhạc số Việt Nam nhiều tuần, hàng trăm triệu view",
        "intro": "Jack sinh ngày 05/01/1997 — khuôn mặt điền trai, ánh mắt buồn man mác, giọng hát đặc trưng không lẫn vào đâu. 'Muộn Rồi Mà Sao Còn' triệu view, 'Sóng Gió' là bài đôi ăn ý nhất V-pop. Vừa muốn bảo vệ anh vừa muốn được bảo vệ — mâu thuẫn nhưng đúng!",
        "image_url": "", "tags": ["V-pop", "ballad"],
    },

    # ── 🇰🇷 BTS ───────────────────────────────────────────────────────────────
    {
        "name": "V (Kim Taehyung)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Ca sĩ (BTS)",
        "birthday": "30/12/1995", "height": "1m79", "weight": "63 kg",
        "blood_type": "AB", "zodiac": "Ma Kết ♑",
        "fav_color": "Xám & Trắng", "fav_number": "10",
        "status": "Đang phục vụ quân sự 🪖",
        "hobbies": "Chụp ảnh phim, hội họa, nhạc jazz/classical, sưu tập đồ cổ",
        "top_works": "Album 'Layover' (#1 Billboard 200), 'Stigma', 'Singularity', 'Sweet Night' (OST Itaewon Class)",
        "awards": "Grammy nomination, Daesang MAMA/Melon, Billboard Artist of the Year",
        "intro": "V sinh ngày 30/12/1995 — được tạp chí GQ, Vogue, Hollywood Reporter bình chọn đẹp trai nhất thế giới nhiều lần. Khuôn mặt đối xứng hoàn hảo, giọng baritone trầm ấm hiếm có. Nhiếp ảnh gia tài năng và collector đồ cổ nghiêm túc. Solo album 'Layover' phá kỷ lục nhiều nước.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Kim_Tae-hyung_at_the_2023_Melon_Music_Awards_%28cropped%29.jpg/440px-Kim_Tae-hyung_at_the_2023_Melon_Music_Awards_%28cropped%29.jpg",
        "tags": ["K-pop", "BTS", "visual icon"],
    },
    {
        "name": "Jungkook",
        "origin": "Hàn Quốc 🇰🇷", "job": "Ca sĩ (BTS)",
        "birthday": "01/09/1997", "height": "1m78", "weight": "70 kg",
        "blood_type": "A", "zodiac": "Xử Nữ ♍",
        "fav_color": "Đen & Trắng", "fav_number": "1",
        "status": "Đang phục vụ quân sự 🪖",
        "hobbies": "Gym (tập rất nặng), vẽ, nhiếp ảnh, nấu ăn, video game",
        "top_works": "'Seven' (#1 Billboard Hot 100), 'Standing Next to You', album 'Golden'",
        "awards": "#1 Billboard Hot 100, MTV VMAs, Grammy nomination, AMA, Billboard Music Awards",
        "intro": "Jungkook sinh ngày 01/09/1997 — 'Golden Maknae' với tài năng toàn diện. Body gym 6-pack khiến cả internet ngừng thở. 'Seven' là ca khúc solo Hàn Quốc đầu tiên giữ #1 Billboard Hot 100 trong 8 tuần liên tiếp — kỷ lục lịch sử!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/230916_Jungkook_Shoot_1_%28cropped%29.jpg/440px-230916_Jungkook_Shoot_1_%28cropped%29.jpg",
        "tags": ["K-pop", "BTS", "6-pack 🔥"],
    },
    {
        "name": "Jin (Kim Seokjin)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Ca sĩ (BTS)",
        "birthday": "04/12/1992", "height": "1m79", "weight": "63 kg",
        "blood_type": "O", "zodiac": "Nhân Mã ♐",
        "fav_color": "Hồng & Đen", "fav_number": "4",
        "status": "Xuất ngũ 06/2024, độc thân 💫",
        "hobbies": "Chơi game (Overwatch), nấu ăn, câu cá, hài hước",
        "top_works": "'The Astronaut', 'Epiphany', 'Awake', 'Super Tuna' (viral meme toàn cầu)",
        "awards": "Grammy nomination, Daesang MAMA/Melon/MMA, Billboard Music Awards",
        "intro": "Jin sinh ngày 04/12/1992 — tự phong 'Worldwide Handsome' và cả thế giới đồng ý. Xuất ngũ với body đỉnh hơn trước khi đi — quân đội Hàn Quốc là gym tốt nhất! Giọng tenor trong vắt, khiếu hài hước vô đối, nụ cười windshield-wiper iconic.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/BTS_Jin_at_Maison_Fred%2C_13_March_2025_04.png/400px-BTS_Jin_at_Maison_Fred%2C_13_March_2025_04.png", "tags": ["K-pop", "BTS", "Worldwide Handsome"],
    },
    {
        "name": "Jimin (Park Jimin)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Ca sĩ, vũ công (BTS)",
        "birthday": "13/10/1995", "height": "1m75", "weight": "61 kg",
        "blood_type": "A", "zodiac": "Thiên Bình ♎",
        "fav_color": "Đen & Xám", "fav_number": "3",
        "status": "Đang phục vụ quân sự 🪖",
        "hobbies": "Nhảy contemporary, boxing, chăm sóc bản thân",
        "top_works": "Album 'FACE', 'Like Crazy' (#1 Billboard Hot 100), 'Set Me Free Pt. 2', 'Vibe'",
        "awards": "#1 Billboard Hot 100, Grammy nomination, Melon Daesang, Global Icon Award",
        "intro": "Jimin sinh ngày 13/10/1995 — nghệ sĩ solo người Hàn đầu tiên đạt #1 Billboard Hot 100 với 'Like Crazy'. Kỹ thuật nhảy contemporary đỉnh cao, biểu cảm sân khấu cuốn hút không ai cưỡng lại. Visible abs từ những lần fancam viral gây sốt toàn cầu.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/3/33/Jimin_on_the_way_to_SBS_Radio%2C_31_March_2023_%282%29.jpg", "tags": ["K-pop", "BTS", "dancer"],
    },
    {
        "name": "RM (Kim Namjoon)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Rapper, leader (BTS)",
        "birthday": "12/09/1994", "height": "1m81", "weight": "67 kg",
        "blood_type": "A", "zodiac": "Xử Nữ ♍",
        "fav_color": "Bạc & Trắng", "fav_number": "1",
        "status": "Xuất ngũ 06/2025, độc thân 💫",
        "hobbies": "Tham quan bảo tàng, sưu tập nghệ thuật, đọc sách triết học, viết nhật ký",
        "top_works": "Album solo 'Indigo' (2022), 'Wild Flower', phát biểu tại LHQ (UN Speech 2018/2021)",
        "awards": "Grammy nomination, Billboard Music Awards, Grammy Foundation Award",
        "intro": "RM sinh ngày 12/09/1994 — leader BTS, IQ 148, tự học tiếng Anh qua xem 'Friends'. Collector nghệ thuật đương đại nghiêm túc, hiến tặng cho các bảo tàng quốc gia Hàn Quốc. Phát biểu tại Đại Hội Đồng LHQ năm 2018 và 2021. Cao 1m81, lúm đồng tiền hai bên má siêu cute.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/RM_at_W_Korea_Love_Your_W%2C_November_2023.jpg/400px-RM_at_W_Korea_Love_Your_W%2C_November_2023.jpg", "tags": ["K-pop", "BTS", "rapper", "intellectual"],
    },
    {
        "name": "J-Hope (Jung Hoseok)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Rapper, dancer (BTS)",
        "birthday": "18/02/1994", "height": "1m77", "weight": "65 kg",
        "blood_type": "A", "zodiac": "Bảo Bình ♒",
        "fav_color": "Xanh lá & Vàng", "fav_number": "7",
        "status": "Xuất ngũ 10/2024, độc thân 💫",
        "hobbies": "Nhảy đường phố, thời trang, sản xuất nhạc, gym",
        "top_works": "Album 'Jack in the Box' (2022), 'MORE', headline Lollapalooza 2022, 'ON THE STREET'",
        "awards": "Grammy nomination, Billboard Music Awards, headline festival quốc tế",
        "intro": "J-Hope sinh ngày 18/02/1994 — 'sunshine' của BTS với năng lượng dồi dào không giới hạn. Nghệ sĩ Hàn Quốc đầu tiên headline solo tại Lollapalooza 2022 (festival âm nhạc lớn Mỹ). Nhảy đường phố đỉnh, phong cách thời trang táo bạo. Xuất ngũ về là anh bùng cháy ngay!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/J-Hope_at_W_Korea_Breast_Cancer_Campaign%2C_15_October_2025.png/400px-J-Hope_at_W_Korea_Breast_Cancer_Campaign%2C_15_October_2025.png", "tags": ["K-pop", "BTS", "dancer"],
    },

    # ── 🇰🇷 EXO ───────────────────────────────────────────────────────────────
    {
        "name": "Baekhyun (Byun Baekhyun)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Ca sĩ (EXO), solo",
        "birthday": "06/05/1992", "height": "1m75", "weight": "61 kg",
        "blood_type": "O", "zodiac": "Kim Ngưu ♉",
        "fav_color": "Trắng & Đen", "fav_number": "6",
        "status": "Xuất ngũ 2023, độc thân 💫",
        "hobbies": "Chơi game, làm nhạc, xem anime, gym",
        "top_works": "Album solo 'City Lights', 'Delight' (1M copies), 'Bambi', EXO 'Ko Ko Bop'",
        "awards": "Daesang MAMA/Melon, Gaon Chart Awards, Bonsang Golden Disc/Seoul Music Awards",
        "intro": "Baekhyun sinh ngày 06/05/1992 — vocal main EXO, nghệ sĩ solo bán hơn 1 triệu album mỗi comeback. Nụ cười mắt híp ngây thơ, aegyo hàng đầu K-pop nhưng lên sân khấu thì charisma hoàn toàn khác. Xuất ngũ xong bùng cháy trở lại không kịp thở!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/%ED%95%98%EC%96%80%EB%A8%B8%EB%A6%AC_%EB%B0%B1%ED%98%84_3.jpg/400px-%ED%95%98%EC%96%80%EB%A8%B8%EB%A6%AC_%EB%B0%B1%ED%98%84_3.jpg", "tags": ["K-pop", "EXO", "solo artist"],
    },
    {
        "name": "Kai (Kim Jongin)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Ca sĩ, dancer (EXO)",
        "birthday": "14/01/1994", "height": "1m82", "weight": "66 kg",
        "blood_type": "A", "zodiac": "Ma Kết ♑",
        "fav_color": "Đen & Vàng ánh kim", "fav_number": "2",
        "status": "Xuất ngũ 2024, độc thân 💫",
        "hobbies": "Múa ballet (tập từ nhỏ), xem phim nghệ thuật, đọc văn học cổ điển, gym",
        "top_works": "EXO 'Tempo', 'Power'; solo 'KAI', 'Peaches', 'Rover'",
        "awards": "Daesang MAMA/Melon (với EXO), MTV VMAs, Vogue Korea/Harper's Bazaar cover",
        "intro": "Kai sinh ngày 14/01/1994 — main dancer EXO, tập ballet từ nhỏ nên body và di chuyển sân khấu uyển chuyển đẳng cấp cao. Solo album 'Peaches' được tạp chí Vogue đánh giá như một tác phẩm nghệ thuật thật sự. Global ambassador của Gucci — không phải ngẫu nhiên!",
        "image_url": "", "tags": ["K-pop", "EXO", "dancer", "Gucci"],
    },
    {
        "name": "Sehun (Oh Sehun)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Ca sĩ (EXO), diễn viên",
        "birthday": "12/04/1994", "height": "1m83", "weight": "65 kg",
        "blood_type": "B", "zodiac": "Bạch Dương ♈",
        "fav_color": "Đen & Trắng", "fav_number": "4",
        "status": "Đang phục vụ quân sự 🪖",
        "hobbies": "Skateboard, chụp ảnh film, thời trang cao cấp, gym",
        "top_works": "EXO 'Monster', 'Wolf', 'Obsession'; Dolce & Gabbana Global Ambassador",
        "awards": "Daesang MAMA/Melon (với EXO), nhiều giải thưởng thời trang quốc tế",
        "intro": "Sehun sinh ngày 12/04/1994 — maknae EXO, cao nhất nhóm 1m83, global ambassador của Dolce & Gabbana. Visual được xếp vào hàng đẹp trai nhất K-pop qua các thời đại. Mê skateboard và chụp ảnh film — depth thật sự không chỉ là idol image.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Oh_Se-hun_at_Rimowa_Essential_Poly_Color_Collection_Launch_on_July_5%2C_2019.png/400px-Oh_Se-hun_at_Rimowa_Essential_Poly_Color_Collection_Launch_on_July_5%2C_2019.png", "tags": ["K-pop", "EXO", "fashion icon"],
    },
    {
        "name": "Chanyeol (Park Chanyeol)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Ca sĩ, rapper (EXO), nhạc sĩ",
        "birthday": "27/11/1992", "height": "1m85", "weight": "72 kg",
        "blood_type": "A", "zodiac": "Nhân Mã ♐",
        "fav_color": "Đen", "fav_number": "27",
        "status": "Đang phục vụ quân sự 🪖",
        "hobbies": "Sản xuất nhạc (tự làm beat), chơi guitar/piano/drum, gym",
        "top_works": "EXO 'Power', 'Tempo', 'Ko Ko Bop'; solo 'Tomorrow', 'SSFW'",
        "awards": "Daesang MAMA/Melon (với EXO), nhiều giải thưởng âm nhạc Hàn Quốc",
        "intro": "Chanyeol sinh ngày 27/11/1992 — rapper EXO, tự sản xuất âm nhạc nghiêm túc. Giọng rap trầm đặc trưng, chơi được guitar/piano/drum thật sự. Body cao to 1m85 rắn chắc. Nụ cười chiều rộng iconic — có thể làm bất cứ ai rung động chỉ bằng một nụ cười!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Chanyeol_during_the_Exo_Planet_5_%E2%80%93_Exploration_concert_on_December_2019.jpg/400px-Chanyeol_during_the_Exo_Planet_5_%E2%80%93_Exploration_concert_on_December_2019.jpg", "tags": ["K-pop", "EXO", "nhạc sĩ"],
    },

    # ── 🇰🇷 Stray Kids ────────────────────────────────────────────────────────
    {
        "name": "Felix (Lee Yongbok)",
        "origin": "Úc 🇦🇺 / Hàn Quốc 🇰🇷", "job": "Ca sĩ, dancer (Stray Kids)",
        "birthday": "15/09/2000", "height": "1m75", "weight": "62 kg",
        "blood_type": "AB", "zodiac": "Xử Nữ ♍",
        "fav_color": "Đen & Vàng", "fav_number": "9",
        "status": "Độc thân 💫",
        "hobbies": "Nấu ăn, vẽ, gym, xem phim, chơi với thú cưng",
        "top_works": "SKZ 'MIROH', 'God's Menu', 'MANIAC', 'S-Class', solo stage 'Latchkey'",
        "awards": "Daesang MAMA/Melon (với SKZ), Billboard Music Awards, MTV VMAs",
        "intro": "Felix sinh ngày 15/09/2000 — người Úc gốc Hàn với làn da trắng muốt, tàn nhang siêu cute và giọng bass trầm 'không thuộc về người thường'. Vũ đạo bùng nổ, năng lượng sân khấu đỉnh cao. Ngoài đời nấu ăn ngon, yêu gia đình và tử tế không giới hạn.",
        "image_url": "", "tags": ["K-pop", "Stray Kids", "performer"],
    },
    {
        "name": "Hyunjin (Hwang Hyunjin)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Ca sĩ, họa sĩ (Stray Kids)",
        "birthday": "20/03/2000", "height": "1m79", "weight": "65 kg",
        "blood_type": "A", "zodiac": "Song Ngư ♓",
        "fav_color": "Đen & Trắng & Tím nhạt", "fav_number": "20",
        "status": "Độc thân 💫",
        "hobbies": "Hội họa sơn dầu, viết nhạc, chụp ảnh nghệ thuật, nhảy",
        "top_works": "SKZ 'MIROH', 'Thunderous', 'MIROH'; tranh sơn dầu đấu giá từ thiện hàng trăm triệu won",
        "awards": "Daesang MAMA, MTV VMAs; tranh đấu giá 200+ triệu won cho từ thiện",
        "intro": "Hyunjin sinh ngày 20/03/2000 — visual chính SKZ, khuôn mặt như tranh vẽ. Tài năng hội họa thật sự — tranh sơn dầu đấu giá thu về hàng trăm triệu won cho từ thiện. Múa đẹp như nghệ sĩ đương đại, nghệ sĩ toàn diện không thể gắn nhãn 'chỉ là idol'.",
        "image_url": "", "tags": ["K-pop", "Stray Kids", "họa sĩ"],
    },

    # ── 🇰🇷 TXT, NCT, ENHYPEN, SEVENTEEN ─────────────────────────────────────
    {
        "name": "Yeonjun (Choi Yeonjun)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Ca sĩ, dancer (TXT)",
        "birthday": "13/09/1999", "height": "1m81", "weight": "67 kg",
        "blood_type": "AB", "zodiac": "Xử Nữ ♍",
        "fav_color": "Đen & Đỏ", "fav_number": "13",
        "status": "Độc thân 💫",
        "hobbies": "Viết nhạc, fashion styling, gym, streaming games",
        "top_works": "TXT 'Good Boy Gone Bad', 'Sugar Rush Ride'; solo 'LOCA', 'Chasing That Feeling'",
        "awards": "MAMA Rookie/Daesang (với TXT), Melon Music Awards, MTV VMAs",
        "intro": "Yeonjun sinh ngày 13/09/1999 — center và main dancer TXT, một trong những vũ công xuất sắc nhất 4th gen K-pop. Cao 1m81, phong thái lạnh lùng trên sân khấu nhưng rất vui tính ngoài đời. Bias wrecker #1 TXT fandom!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Yeonjun_250625.jpg/400px-Yeonjun_250625.jpg", "tags": ["K-pop", "TXT", "dancer"],
    },
    {
        "name": "Wonwoo (Jeon Wonwoo)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Rapper (SEVENTEEN)",
        "birthday": "17/07/1996", "height": "1m80", "weight": "67 kg",
        "blood_type": "A", "zodiac": "Cự Giải ♋",
        "fav_color": "Đen & Xanh tối", "fav_number": "17",
        "status": "Độc thân 💫",
        "hobbies": "Đọc sách (mọt sách chính gốc), triết học, viết nhạc, gym",
        "top_works": "SEVENTEEN 'Left & Right', 'Rock with You'; unit MINGYU x WONWOO",
        "awards": "Daesang MAMA/Melon (với SVT), Billboard Global 200",
        "intro": "Wonwoo sinh ngày 17/07/1996 — rapper SEVENTEEN với phong thái lạnh lùng bí ẩn nhưng siêu funny khi livestream. Khuôn mặt góc cạnh sắc bén, mắt một mí hút hồn, giọng rap trầm đặc trưng. Mọt sách nghiêm túc, thích triết học — depth không chỉ ở visual!",
        "image_url": "", "tags": ["K-pop", "SEVENTEEN", "rapper"],
    },
    {
        "name": "Taeyong (Lee Taeyong)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Rapper (NCT 127)",
        "birthday": "01/07/1995", "height": "1m76", "weight": "62 kg",
        "blood_type": "A", "zodiac": "Cự Giải ♋",
        "fav_color": "Đen", "fav_number": "1",
        "status": "Xuất ngũ 2025, độc thân 💫",
        "hobbies": "Thiết kế trang sức, vẽ graffiti, gym, nấu ăn",
        "top_works": "NCT 127 'Kick It', 'Cherry Bomb', 'Simon Says'; solo 'SHALALA'",
        "awards": "Daesang MAMA/Gaon (với NCT 127), MTV VMAs, Billboard Chart",
        "intro": "Taeyong sinh ngày 01/07/1995 — leader NCT 127, visual số 1 SM Entertainment. Khuôn mặt như điêu khắc, vũ đạo sharp tuyệt đối, rap rõ từng chữ. Thiết kế đồ trang sức và vẽ graffiti ngoài âm nhạc. Bộ tổng Taeyong hiếm có!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/20231006_Taeyong_%28NCT%29.jpg/400px-20231006_Taeyong_%28NCT%29.jpg", "tags": ["K-pop", "NCT", "visual"],
    },
    {
        "name": "Mark Lee (이마크)",
        "origin": "Canada 🇨🇦 / NCT", "job": "Rapper (NCT 127/Dream)",
        "birthday": "02/08/1999", "height": "1m76", "weight": "63 kg",
        "blood_type": "O", "zodiac": "Sư Tử ♌",
        "fav_color": "Đen & Trắng", "fav_number": "2",
        "status": "Độc thân 💫",
        "hobbies": "Viết rap, gym, cooking (nấu ăn rất ngon), học tiếng Trung",
        "top_works": "NCT 127 'Kick It', 'Superhuman'; NCT Dream 'Hot Sauce'; SuperM 'Jopping'",
        "awards": "Grammy nomination (SuperM), Daesang MAMA (với NCT), nhiều giải SM",
        "intro": "Mark Lee sinh ngày 02/08/1999 — rapper Canada gốc Hàn, thành viên NCT 127, NCT Dream và SuperM cùng lúc. Năng lượng dồi dào, tích cực vô hạn, rap nhanh mà rõ. Nấu ăn ngon bất ngờ và thẳng thắn hài hước không cần filter. Crush của cả SM Town!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/20231006_Mark_%28NCT%29.jpg/400px-20231006_Mark_%28NCT%29.jpg", "tags": ["K-pop", "NCT", "rapper"],
    },
    {
        "name": "Jay (Park Jongseong)",
        "origin": "Mỹ 🇺🇸 / ENHYPEN", "job": "Ca sĩ (ENHYPEN)",
        "birthday": "20/04/2002", "height": "1m82", "weight": "68 kg",
        "blood_type": "A", "zodiac": "Bạch Dương ♈",
        "fav_color": "Đen & Xanh dương", "fav_number": "20",
        "status": "Độc thân 💫",
        "hobbies": "Gym (tập rất nghiêm túc), viết rap, basketball",
        "top_works": "ENHYPEN 'Given-Taken', 'Bite Me', 'Sweet Venom'; solo 'BÊTE NOIRE'",
        "awards": "MAMA Rookie, Melon Music Awards, Golden Disc Awards (với ENHYPEN)",
        "intro": "Jay sinh ngày 20/04/2002 — người Mỹ gốc Hàn trong ENHYPEN, nói 4 thứ tiếng, tập gym cực nghiêm túc. Body rắn chắc nhất ENHYPEN với visible abs. Thẳng thắn và hài hước không cần filter. Bad boy với trái tim tốt — ngầu trên sân khấu, cười toe toét ngoài đời.",
        "image_url": "", "tags": ["K-pop", "ENHYPEN", "6-pack 🔥"],
    },
    {
        "name": "Cha Eunwoo (Lee Dongmin)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Ca sĩ (ASTRO), diễn viên",
        "birthday": "30/03/1997", "height": "1m83", "weight": "72 kg",
        "blood_type": "O", "zodiac": "Bạch Dương ♈",
        "fav_color": "Trắng & Xanh nhạt", "fav_number": "3",
        "status": "Độc thân 💫",
        "hobbies": "Đọc sách, học ngoại ngữ, gym, bơi lội",
        "top_works": "Drama 'True Beauty' (2020), 'My ID is Gangnam Beauty', 'A Good Day to be a Dog' (2023)",
        "awards": "Baeksang Arts Awards đề cử, Asia Artist Awards, APAN Star Awards",
        "intro": "Cha Eunwoo sinh ngày 30/03/1997 — mệnh danh 'Real Life Manhwa Character' vì khuôn mặt cực kỳ đối xứng và hoàn hảo đến mức không tin là có thật. Cử nhân ĐH Sungkyunkwan ngành Kỹ thuật điện — đẹp mà còn học giỏi. 'True Beauty' gây bão MXH toàn châu Á.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Cha_Eun-woo%2C_March_31%2C_2025.png/400px-Cha_Eun-woo%2C_March_31%2C_2025.png", "tags": ["K-pop", "ASTRO", "visual legend"],
    },

    # ── 🇰🇷 K-drama actors ────────────────────────────────────────────────────
    {
        "name": "Park Bogum",
        "origin": "Hàn Quốc 🇰🇷", "job": "Diễn viên, ca sĩ",
        "birthday": "16/06/1993", "height": "1m82", "weight": "68 kg",
        "blood_type": "A", "zodiac": "Song Tử ♊",
        "fav_color": "Xanh nhạt & Trắng", "fav_number": "16",
        "status": "Xuất ngũ 2022, độc thân 💫",
        "hobbies": "Chơi piano (rất giỏi), thể dục, âm nhạc jazz, thiện nguyện",
        "top_works": "Drama 'Reply 1988' (2015), 'Moonlight Drawn by Clouds' (2016), 'Record of Youth' (2020)",
        "awards": "Baeksang Arts Awards (Nam diễn viên nổi tiếng), KBS Drama Awards (Nam chính)",
        "intro": "Park Bogum sinh ngày 16/06/1993 — mẫu nam thần Hàn hoàn hảo nhất: đẹp, tài, tử tế và chân thành. Chơi piano cực giỏi, màn biểu diễn tại fansign viral khắp mạng. 'Reply 1988' và 'Moonlight' đưa anh vào lòng hàng triệu khán giả châu Á.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Park_Bo-gum_%EB%B0%95%EB%B3%B4%EA%B2%80_%E6%9C%B4%E5%AF%B6%E5%8A%8D_for_Marie_Claire_Korea%2C_April_2025_4.png/400px-Park_Bo-gum_%EB%B0%95%EB%B3%B4%EA%B2%80_%E6%9C%B4%E5%AF%B6%E5%8A%8D_for_Marie_Claire_Korea%2C_April_2025_4.png", "tags": ["K-drama", "diễn viên", "piano"],
    },
    {
        "name": "Park Seo-jun",
        "origin": "Hàn Quốc 🇰🇷", "job": "Diễn viên",
        "birthday": "16/12/1988", "height": "1m82", "weight": "74 kg",
        "blood_type": "AB", "zodiac": "Nhân Mã ♐",
        "fav_color": "Đen & Trắng", "fav_number": "7",
        "status": "Độc thân 💫",
        "hobbies": "Gym (tập rất nghiêm túc), thể thao, cooking",
        "top_works": "Drama 'What's Wrong with Secretary Kim' (2018), 'Itaewon Class' (2020), Marvel 'The Marvels' (2023)",
        "awards": "SBS Drama Awards (Nam chính), tvN Drama Awards, Baeksang đề cử",
        "intro": "Park Seo-jun sinh ngày 16/12/1988 — body gym 6-pack visible trong nhiều cảnh quay. 'Itaewon Class' viral toàn cầu trên Netflix, sau đó gia nhập Marvel. Drama nào có Park Seo-jun là chị em coi không bỏ tập nào!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Park_Seo-joon_in_March_2026.png/400px-Park_Seo-joon_in_March_2026.png", "tags": ["K-drama", "Marvel 🎬", "6-pack 🔥"],
    },
    {
        "name": "Kim Soo-hyun",
        "origin": "Hàn Quốc 🇰🇷", "job": "Diễn viên",
        "birthday": "16/02/1988", "height": "1m82", "weight": "70 kg",
        "blood_type": "A", "zodiac": "Bảo Bình ♒",
        "fav_color": "Xanh navy & Trắng", "fav_number": "2",
        "status": "Độc thân 💫",
        "hobbies": "Đọc kịch bản, gym, nấu ăn, thiện nguyện im lặng",
        "top_works": "'My Love from the Star' (2013), 'Moon That Embraces the Sun' (2012), 'Queen of Tears' (2024)",
        "awards": "Baeksang Arts Awards (Nam diễn viên xuất sắc), Daesang nhiều lễ trao giải, cát-xê cao nhất HQ",
        "intro": "Kim Soo-hyun sinh ngày 16/02/1988 — được trả cát-xê cao nhất Hàn Quốc, và xứng đáng hoàn toàn. 'My Love from the Star' gây bão 30+ quốc gia. Comeback 2024 với 'Queen of Tears' phá kỷ lục rating tvN. Quốc bảo diễn xuất Hàn Quốc!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Kim_Soo-hyun_in_August_2024_-_2.png/400px-Kim_Soo-hyun_in_August_2024_-_2.png", "tags": ["K-drama", "top actor", "icon"],
    },
    {
        "name": "Lee Min-ho",
        "origin": "Hàn Quốc 🇰🇷", "job": "Diễn viên",
        "birthday": "22/06/1987", "height": "1m87", "weight": "75 kg",
        "blood_type": "A", "zodiac": "Cự Giải ♋",
        "fav_color": "Đen & Xám", "fav_number": "22",
        "status": "Độc thân 💫",
        "hobbies": "Guitar, gym, thể thao, đọc tiểu thuyết",
        "top_works": "'Boys Over Flowers' (2009), 'The Heirs' (2013), 'The King: Eternal Monarch' (2020)",
        "awards": "Baeksang Arts Awards đề cử, Top Hallyu Star nhiều năm, QQ Asian Style Award",
        "intro": "Lee Min-ho sinh ngày 22/06/1987, cao 1m87 — người đàn ông đưa Hallyu wave đến Việt Nam qua 'Boys Over Flowers'. Cao nhất danh sách K-drama hôm nay, khuôn mặt điêu khắc hoàn hảo. Sau 15+ năm sự nghiệp, vẫn là biểu tượng Hallyu không thể thay thế.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Lee_Min-ho_in_December_2025.png/400px-Lee_Min-ho_in_December_2025.png", "tags": ["K-drama", "Hallyu icon", "diễn viên"],
    },
    {
        "name": "Gong Yoo",
        "origin": "Hàn Quốc 🇰🇷", "job": "Diễn viên",
        "birthday": "10/07/1979", "height": "1m84", "weight": "76 kg",
        "blood_type": "A", "zodiac": "Cự Giải ♋",
        "fav_color": "Đen & Trắng & Nâu", "fav_number": "10",
        "status": "Độc thân 💫",
        "hobbies": "Gym (tập rất nặng), đọc sách, cafe, thể thao ngoài trời",
        "top_works": "'Coffee Prince' (2007), 'Goblin' (2016 — 20.5% rating), 'Train to Busan' (2016)",
        "awards": "Baeksang Arts Awards (Nam diễn xuất xuất sắc), Korean Drama Awards, Asia Artist Awards",
        "intro": "Gong Yoo sinh ngày 10/07/1979 — body gym 6-pack iconic của showbiz Hàn. 'Goblin' phá kỷ lục tvN với 20.5% rating, Gong Yoo trong áo vest cầm hoa cải = biểu tượng K-drama lãng mạn. Tuổi 40+ vẫn đỉnh cao không nghi ngờ!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Gong_Yoo_in_2021_-_3.png/400px-Gong_Yoo_in_2021_-_3.png", "tags": ["K-drama", "diễn viên", "6-pack 🔥"],
    },
    {
        "name": "Lee Junho (이준호)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Ca sĩ (2PM), diễn viên",
        "birthday": "25/01/1990", "height": "1m77", "weight": "65 kg",
        "blood_type": "A", "zodiac": "Ma Kết ♑",
        "fav_color": "Xanh dương & Trắng", "fav_number": "6",
        "status": "Xuất ngũ 2023, độc thân 💫",
        "hobbies": "Vẽ (nghệ sĩ thật sự), sản xuất nhạc, gym",
        "top_works": "Drama 'The Red Sleeve' (2021 — rating kỷ lục MBC 17.4%), 2PM 'Heartbeat'",
        "awards": "MBC Drama Awards (Daesang diễn xuất), Baeksang đề cử",
        "intro": "Junho sinh ngày 25/01/1990 — nghệ sĩ toàn diện: hát, nhảy, rap, diễn, vẽ tranh. 'The Red Sleeve' phá kỷ lục rating MBC với 17.4%, Junho nhận Daesang diễn xuất — chứng minh idol có thể trở thành diễn viên thật sự. Xuất ngũ về là fan xếp hàng chờ comeback!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Lee_Jun-ho_%EC%9D%B4%EC%A4%80%ED%98%B8_211228.png/400px-Lee_Jun-ho_%EC%9D%B4%EC%A4%80%ED%98%B8_211228.png", "tags": ["K-pop", "2PM", "diễn viên"],
    },
    {
        "name": "Son Heung-min (손흥민)",
        "origin": "Hàn Quốc 🇰🇷", "job": "Cầu thủ (Tottenham Hotspur)",
        "birthday": "08/07/1992", "height": "1m83", "weight": "78 kg",
        "blood_type": "A", "zodiac": "Cự Giải ♋",
        "fav_color": "Xanh lam Tottenham", "fav_number": "7",
        "status": "Độc thân 💫",
        "hobbies": "Golf, nấu ăn Hàn Quốc, game, nghỉ ngơi chất lượng",
        "top_works": "Premier League Golden Boot 2022, 100 bàn thắng Tottenham, captain ĐTQG Hàn Quốc",
        "awards": "FWA Footballer of the Year 2022, Asian Footballer of the Year, PL Player of the Month nhiều lần",
        "intro": "Son Heung-min sinh ngày 08/07/1992 — cầu thủ xuất sắc nhất châu Á, chia sẻ Vua phá lưới Premier League 2022 với Salah. Ngoài sân cỏ: tử tế, khiêm tốn, và cực kỳ đẹp trai kiểu trai lành mạnh. Captain tuyển Hàn Quốc và là niềm tự hào quốc gia!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/BFA_2023_-2_Heung-Min_Son_%28cropped%29.jpg/400px-BFA_2023_-2_Heung-Min_Son_%28cropped%29.jpg", "tags": ["bóng đá ⚽", "Premier League", "icon"],
    },

    # ── 🇨🇳 C-pop & C-drama ───────────────────────────────────────────────────
    {
        "name": "Vương Nhất Bác (Wang Yibo)",
        "origin": "Trung Quốc 🇨🇳", "job": "Ca sĩ, diễn viên, đua xe",
        "birthday": "05/08/1997", "height": "1m82", "weight": "66 kg",
        "blood_type": "O", "zodiac": "Sư Tử ♌",
        "fav_color": "Đen & Trắng & Đỏ", "fav_number": "8",
        "status": "Độc thân 💫",
        "hobbies": "Đua xe mô tô (chuyên nghiệp), nhảy, chơi game, thể thao mạo hiểm",
        "top_works": "'Trần Tình Lệnh' (2019), 'Phong Khởi Lạc Dương', 'Trường Tân' (phim điện ảnh)",
        "awards": "Weibo Movie Awards, Golden Eagle Awards, đua xe CMSC giải nhất nhiều lần",
        "intro": "Vương Nhất Bác sinh ngày 05/08/1997 — vibe lạnh lùng ngầu, body rắn chắc từ tập nhảy và đua xe mô tô chuyên nghiệp. Nhìn thẳng vào camera khiến người xem quên mất đang thở. 'Trần Tình Lệnh' bùng nổ toàn châu Á 2019.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/20200111%E7%8E%8B%E4%B8%80%E5%8D%9A.jpg/400px-20200111%E7%8E%8B%E4%B8%80%E5%8D%9A.jpg", "tags": ["C-pop", "diễn viên", "đua xe 🏍️"],
    },
    {
        "name": "Tiêu Chiến (Xiao Zhan)",
        "origin": "Trung Quốc 🇨🇳", "job": "Ca sĩ, diễn viên",
        "birthday": "05/10/1991", "height": "1m84", "weight": "68 kg",
        "blood_type": "AB", "zodiac": "Thiên Bình ♎",
        "fav_color": "Trắng & Xanh nhạt", "fav_number": "5",
        "status": "Độc thân 💫",
        "hobbies": "Vẽ tranh minh họa (học thiết kế đồ họa), nấu ăn, nhạc acoustic",
        "top_works": "'Trần Tình Lệnh' (2019 — phim gây bão nhất thập kỷ), 'Chiến Lang', 'Thương Lan Quyết'",
        "awards": "Weibo Star Awards, Golden Eagle Awards, MTV Chinese Music Awards",
        "intro": "Tiêu Chiến sinh ngày 05/10/1991, cao 1m84 — xuất thân thiết kế đồ họa trước khi trở thành ngôi sao. 'Trần Tình Lệnh' gây bão khắp châu Á. Vẽ tranh đẹp, nấu ăn ngon, nụ cười tỏa nắng — cộng đồng fan VN đông không kém quốc nội!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Xiao_Zhan_at_the_Weibo_Night_Ceremony_January_11_2020.jpg/400px-Xiao_Zhan_at_the_Weibo_Night_Ceremony_January_11_2020.jpg", "tags": ["C-pop", "diễn viên", "icon"],
    },
    {
        "name": "Vương Hạc Đệ (Wang Hedi)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên, ca sĩ",
        "birthday": "07/04/1998", "height": "1m85", "weight": "70 kg",
        "blood_type": "B", "zodiac": "Bạch Dương ♈",
        "fav_color": "Trắng & Vàng nhạt", "fav_number": "7",
        "status": "Độc thân 💫",
        "hobbies": "Bơi lội, piano, thời trang trendy, gym",
        "top_works": "'Một Nụ Cười Vạn Năm' (2018), 'You Are My Hero', 'Where the Wind Blows'",
        "awards": "Tencent Video Awards, Weibo TV Stars Awards, Mango TV Stars Awards",
        "intro": "Vương Hạc Đệ sinh ngày 07/04/1998, cao 1m85 — nụ cười năng lượng cao, mái tóc bồng bềnh. Body bơi lội tỷ lệ vai-eo hoàn hảo. Vibe của anh = muôn ánh mặt trời buổi sáng không thể cưỡng lại!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Dylan_Wang.jpg/400px-Dylan_Wang.jpg", "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Cung Tuấn (Gong Jun)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên, ca sĩ",
        "birthday": "11/02/1992", "height": "1m86", "weight": "75 kg",
        "blood_type": "A", "zodiac": "Bảo Bình ♒",
        "fav_color": "Xanh rêu & Đen", "fav_number": "11",
        "status": "Độc thân 💫",
        "hobbies": "Cắm trại, leo núi, nấu ăn, gym, photography thiên nhiên",
        "top_works": "'Sơn Hà Lệnh' (2021), 'Where Dreams Begin', 'Fearless' (MV solo)",
        "awards": "Weibo Drama Awards, iQiyi Drama Awards, Golden Eagle TV Arts Festival",
        "intro": "Cung Tuấn sinh ngày 11/02/1992, cao 1m86 — bùng nổ với vai Chu Bảo Thần trong 'Sơn Hà Lệnh'. Body leo núi và gym cho tỷ lệ rất đẹp. Khuôn mặt phúc hậu, nụ cười ấm lòng. Fan VN gọi yêu là 'Tuấn Tuấn'!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/GJ_Cannes.jpg/400px-GJ_Cannes.jpg", "tags": ["C-pop", "diễn viên", "tall 🏔️"],
    },
    {
        "name": "Lý Hiện (Li Xian)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên",
        "birthday": "27/08/1991", "height": "1m85", "weight": "73 kg",
        "blood_type": "B", "zodiac": "Xử Nữ ♍",
        "fav_color": "Xám & Xanh dương", "fav_number": "6",
        "status": "Độc thân 💫",
        "hobbies": "Đọc sách, nấu ăn, gym, bóng rổ",
        "top_works": "'Go Ahead' (2020 — cả ĐNA khóc hết nước mắt), 'My Marvellous Fable', 'Be Together'",
        "awards": "Weibo TV Drama Awards, iQiyi Starlight Awards, Golden Eagle TV Arts Festival",
        "intro": "Lý Hiện sinh ngày 27/08/1991, cao 1m85 — vai Giang Thần Thành trong 'Go Ahead' khiến cả Đông Nam Á khóc. Body gym đẹp với visible abs, nhưng vẫn giữ được phong thái điềm tĩnh chín chắn. Sự trưởng thành và thực lực có sức hút riêng không kém visual!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Li_Xian_%28cropped%29.jpg/400px-Li_Xian_%28cropped%29.jpg", "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Dương Dương (Yang Yang)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên",
        "birthday": "09/09/1991", "height": "1m84", "weight": "68 kg",
        "blood_type": "O", "zodiac": "Xử Nữ ♍",
        "fav_color": "Trắng & Xanh dương nhạt", "fav_number": "9",
        "status": "Độc thân 💫",
        "hobbies": "Thư pháp, wushu (từ nhỏ), đọc sách, gym",
        "top_works": "'Love O2O' (2016 — viral toàn cầu), 'You Are My City and Fortress' (2022)",
        "awards": "Mao Dun Literature Prize (adaptation), Golden Eagle TV Arts Festival",
        "intro": "Dương Dương sinh ngày 09/09/1991, cao 1m84 — tốt nghiệp Học viện Nghệ thuật Nhân dân TQ, thành thạo wushu từ nhỏ. 'Love O2O' viral toàn cầu. Khuôn mặt sắc nét góc cạnh, ánh mắt sâu — kiêu kỳ nhưng thực lực không thể phủ nhận.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Yang_profile_pic.jpg/400px-Yang_profile_pic.jpg", "tags": ["C-pop", "diễn viên", "wushu"],
    },
    {
        "name": "La Vân Hi (Luo Yunxi)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên, vũ công",
        "birthday": "28/06/1988", "height": "1m80", "weight": "67 kg",
        "blood_type": "A", "zodiac": "Cự Giải ♋",
        "fav_color": "Trắng & Bạc", "fav_number": "3",
        "status": "Độc thân 💫",
        "hobbies": "Múa cổ điển, viết nhật ký, chụp ảnh, nhạc cổ điển",
        "top_works": "'Hương Mật Tựa Khói Sương' (2018), 'Till the End of the Moon' (2023), 'Stand by Me'",
        "awards": "Weibo Drama Awards, iQiyi Starlight Awards, Golden Eagle TV Arts Festival",
        "intro": "La Vân Hi sinh ngày 28/06/1988 — xuất thân vũ công chuyên nghiệp trước khi diễn xuất. Di chuyển uyển chuyển như nghệ sĩ múa thật sự. 'Hương Mật' và 'Till the End of the Moon' đều là tác phẩm để đời. La Vân Hi càng nhìn càng đẹp — fine wine không lỗi thời!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Luo_Yunxi2025.jpg/400px-Luo_Yunxi2025.jpg", "tags": ["C-pop", "diễn viên", "vũ công"],
    },
    {
        "name": "Hứa Khải (Xu Kai)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên, ca sĩ",
        "birthday": "26/12/1994", "height": "1m87", "weight": "74 kg",
        "blood_type": "A", "zodiac": "Ma Kết ♑",
        "fav_color": "Đen & Xám", "fav_number": "6",
        "status": "Độc thân 💫",
        "hobbies": "Gym (tập rất nặng), bơi lội, piano, photography thời trang",
        "top_works": "'Story of Yanxi Palace' (2018), 'Ancient Love Poetry', 'Reset' (2022)",
        "awards": "Weibo Drama Awards, Mango TV Awards, iQiyi Starlight Awards",
        "intro": "Hứa Khải sinh ngày 26/12/1994, cao 1m87 — cao và đẹp nhất C-drama hiện tại. Body gym 6-pack visible, brand ambassador nhiều thương hiệu thể thao cao cấp. Khuôn mặt tinh anh, vừa đóng lạnh lùng vừa đóng tình lang ngọt ngào đều thuyết phục!",
        "image_url": "", "tags": ["C-pop", "diễn viên", "6-pack 🔥"],
    },
    {
        "name": "Ngô Lỗi (Wu Lei)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên",
        "birthday": "26/12/1999", "height": "1m82", "weight": "68 kg",
        "blood_type": "B", "zodiac": "Ma Kết ♑",
        "fav_color": "Xanh dương & Trắng", "fav_number": "26",
        "status": "Độc thân 💫",
        "hobbies": "Bóng rổ, viết lách, gym, xem phim tài liệu",
        "top_works": "'Sư Thúc' (2021 — top trending Netflix toàn cầu), 'Oath of Love', 'Go Into Your Heart'",
        "awards": "Golden Eagle TV Arts Festival, WeTV Popular Actor Awards",
        "intro": "Ngô Lỗi sinh ngày 26/12/1999, cao 1m82 — thần đồng diễn xuất từ nhỏ. 'Sư Thúc' top trending Netflix toàn cầu 2021. Kiểu đẹp 'hoa thần' tinh tế thanh tú, diễn xuất chín chắn vượt tuổi. Gen Z chính gốc nhưng diễn như lão nghệ sĩ!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Wu_Lei_being_interviewed_in_December_2015_for_C_China.png/400px-Wu_Lei_being_interviewed_in_December_2015_for_C_China.png", "tags": ["C-pop", "diễn viên", "Gen Z"],
    },
    {
        "name": "Trần Phi Vũ (Chen Feiyu)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên, ca sĩ",
        "birthday": "02/02/1999", "height": "1m85", "weight": "70 kg",
        "blood_type": "AB", "zodiac": "Bảo Bình ♒",
        "fav_color": "Trắng & Xanh lam nhạt", "fav_number": "2",
        "status": "Độc thân 💫",
        "hobbies": "Ballet (đào tạo chuyên nghiệp), viết nhật ký, gym, nhạc indie",
        "top_works": "'Ever Night' (2018), 'ZERO' (2022 phim điện ảnh), 'Sword Snow Stride'",
        "awards": "FIRST Youth Film Festival, Weibo New Actor Awards, iQiyi New Generation Awards",
        "intro": "Trần Phi Vũ sinh ngày 02/02/1999, cao 1m85 — con trai đạo diễn Trần Khải Ca, tự gây dựng tên tuổi bằng tài năng thật. Từng học ballet chuyên nghiệp nên body tỷ lệ rất đẹp, di chuyển thanh thoát. Thư sinh nghệ sĩ có chiều sâu thật sự!",
        "image_url": "", "tags": ["C-pop", "diễn viên", "ballet"],
    },
    {
        "name": "Tống Uy Long (Song Weilong)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên, người mẫu",
        "birthday": "24/07/1999", "height": "1m87", "weight": "72 kg",
        "blood_type": "A", "zodiac": "Sư Tử ♌",
        "fav_color": "Đen & Trắng", "fav_number": "24",
        "status": "Độc thân 💫",
        "hobbies": "Bóng rổ, thời trang cao cấp, gym, photography",
        "top_works": "'Because of You' (2020), 'Love in Flames of War', cover Vogue/GQ China",
        "awards": "Weibo New Stars Awards, Mango TV Awards, GQ Men of the Year (thời trang)",
        "intro": "Tống Uy Long sinh ngày 24/07/1999, cao 1m87 — nam thần trẻ đang lên mạnh, cover tạp chí Vogue/GQ China liên tục. Body bóng rổ và gym tỷ lệ vai-eo cực đẹp. Khuôn mặt lạnh lùng ẩn chứa nét lãng mạn — biểu tượng tầm châu lục đang hình thành!",
        "image_url": "", "tags": ["C-pop", "người mẫu", "diễn viên"],
    },
    {
        "name": "Bạch Kính Đình (Bai Jingting)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên",
        "birthday": "28/11/1993", "height": "1m80", "weight": "70 kg",
        "blood_type": "B", "zodiac": "Nhân Mã ♐",
        "fav_color": "Xanh nhạt & Trắng", "fav_number": "8",
        "status": "Độc thân 💫",
        "hobbies": "Bơi lội, đọc sách, ẩm thực, nấu ăn Tứ Xuyên",
        "top_works": "'Forever and Ever' (2021 — viral toàn châu Á), 'Time Flies and You Are Here', 'Skate Into Love'",
        "awards": "Weibo Drama Awards, iQiyi Starlight Awards, Mango TV Awards",
        "intro": "Bạch Kính Đình sinh ngày 28/11/1993, cao 1m80 — kiểu đẹp acquired taste: càng nhìn càng thấy đẹp. Phong thái điềm đạm đáng tin cậy. 'Forever and Ever' viral toàn châu Á — treasure của C-drama!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/57/Bai_Jingting.jpg", "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Nhiệm Gia Luân (Ren Jialun)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên",
        "birthday": "16/11/1986", "height": "1m85", "weight": "75 kg",
        "blood_type": "A", "zodiac": "Bọ Cạp ♏",
        "fav_color": "Đen & Đỏ đậm", "fav_number": "8",
        "status": "Đã kết hôn 💍",
        "hobbies": "Cưỡi ngựa, kiếm thuật (thật sự), gym, đọc lịch sử",
        "top_works": "'The Wolf' (2020), 'Till the End of the Moon' (2023), 'Eternal Love Rain'",
        "awards": "Weibo TV Series Awards, iQiyi Starlight Awards, Golden Eagle Drama Awards",
        "intro": "Nhiệm Gia Luân sinh ngày 16/11/1986, cao 1m85 — khí chất vương giả tự nhiên không cần cố gắng. Cưỡi ngựa và kiếm thuật thật sự (không phải stunt). 'Till the End of the Moon' một phim hai vai đều xuất sắc — mẫu đại nhân quân tử ngôn tình bước ra đời thật!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/%E4%BB%BB%E5%98%89%E5%80%AB_%E6%94%9D%E6%96%BC210711_%E6%AD%90%E7%B1%B3%E8%8C%84%E6%B4%BB%E5%8B%95_in_Nanjing.jpg/400px-%E4%BB%BB%E5%98%89%E5%80%AB_%E6%94%9D%E6%96%BC210711_%E6%AD%90%E7%B1%B3%E8%8C%84%E6%B4%BB%E5%8B%95_in_Nanjing.jpg", "tags": ["C-pop", "diễn viên", "cổ trang"],
    },
    {
        "name": "Sái Từ Khôn (Cai Xukun)",
        "origin": "Trung Quốc 🇨🇳", "job": "Ca sĩ, rapper, vũ công",
        "birthday": "02/08/1998", "height": "1m83", "weight": "68 kg",
        "blood_type": "O", "zodiac": "Sư Tử ♌",
        "fav_color": "Đen & Vàng ánh kim", "fav_number": "2",
        "status": "Độc thân 💫",
        "hobbies": "Bóng rổ (rất giỏi), làm nhạc, thiết kế thời trang, gym",
        "top_works": "Solo 'YOUNG', 'Wait Wait Wait', 'Pull Up'; album 'YOUNG x ABLE'",
        "awards": "Weibo Music Awards, Golden Eagle Popular Actor, nhiều giải âm nhạc TQ",
        "intro": "Cai Xukun sinh ngày 02/08/1998, cao 1m83 — 'Triple Threat' C-pop: hát, nhảy, rap đều đỉnh. Video dribble bóng rổ viral khắp TikTok/Weibo. Charisma sân khấu vô cùng cuốn hút — ra sân khấu là chiếm spotlight!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/KUN_Charlotte_Tilbury_in_Shanghai_January_2026.jpg/400px-KUN_Charlotte_Tilbury_in_Shanghai_January_2026.jpg", "tags": ["C-pop", "idol", "bóng rổ 🏀"],
    },
    {
        "name": "Trần Triết Viễn (Chen Zheyuan)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên",
        "birthday": "20/03/1998", "height": "1m82", "weight": "68 kg",
        "blood_type": "B", "zodiac": "Song Ngư ♓",
        "fav_color": "Trắng & Xanh lam", "fav_number": "20",
        "status": "Độc thân 💫",
        "hobbies": "Nhảy (chuyên nghiệp), gym, photography",
        "top_works": "'Sword Snow Stride' (2021), 'A Journey to Love' (2023 — hot nhất năm)",
        "awards": "Weibo New Stars Awards, Tencent Video Awards, iQiyi New Generation",
        "intro": "Trần Triết Viễn sinh ngày 20/03/1998, cao 1m82 — thần đồng nhảy múa chuyên nghiệp trước khi diễn xuất. Body vũ công đẹp hoàn hảo, di chuyển uyển chuyển. Khuôn mặt trẻ trung, ánh mắt trong sáng sâu thẳm — không thể rời mắt!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Chen_Zheyuan.jpg/400px-Chen_Zheyuan.jpg", "tags": ["C-pop", "diễn viên", "vũ công"],
    },
    {
        "name": "Đặng Vĩ (Deng Wei)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên",
        "birthday": "28/12/1992", "height": "1m85", "weight": "76 kg",
        "blood_type": "O", "zodiac": "Ma Kết ♑",
        "fav_color": "Đen & Xám đậm", "fav_number": "7",
        "status": "Độc thân 💫",
        "hobbies": "Gym (tập rất nặng), boxing, bơi lội",
        "top_works": "'Go Ahead' (2020), 'The Long Night', 'Twisted Fate of Love'",
        "awards": "Weibo TV Drama Awards, iQiyi Starlight Awards",
        "intro": "Đặng Vĩ sinh ngày 28/12/1992, cao 1m85 — body gym và boxing cực kỳ rắn chắc. Khuôn mặt góc cạnh mạnh mẽ, ánh mắt sắc bén. Trong 'Go Ahead' dù vai phụ vẫn gây chú ý lớn. Mẫu nam thần vừa đẹp vừa có aura mạnh mẽ không thể bỏ qua!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Deng_Wei.jpg/400px-Deng_Wei.jpg", "tags": ["C-pop", "diễn viên", "6-pack 🔥"],
    },
    {
        "name": "Chu Nhất Long (Zhu Yilong)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên",
        "birthday": "16/04/1988", "height": "1m80", "weight": "68 kg",
        "blood_type": "AB", "zodiac": "Bạch Dương ♈",
        "fav_color": "Đen & Xanh rêu", "fav_number": "3",
        "status": "Độc thân 💫",
        "hobbies": "Đọc sách triết học, viết nhật ký, thiền định",
        "top_works": "'Guardian' (2018 — gây sốt cộng đồng), 'Nirvana in Fire 2', 'New Life'",
        "awards": "Weibo Drama Awards, iQiyi Popular Awards, Golden Eagle TV Arts Festival",
        "intro": "Chu Nhất Long sinh ngày 16/04/1988, cao 1m80 — trầm lắng ít nói, thích đọc sách triết học. Khi bước vào vai diễn thì charisma bùng phát không cưỡng lại. Từ thiện sang phản diện, từ cổ trang sang hiện đại đều xuất sắc. Càng khám phá càng mê!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Zhu_Yilong_%28%E6%9C%B1%E4%B8%80%E9%BE%99%29_at_the_25th_Shanghai_Television_Festival_-_Magnolia_Awards_in_June_2019.jpg/400px-Zhu_Yilong_%28%E6%9C%B1%E4%B8%80%E9%BE%99%29_at_the_25th_Shanghai_Television_Festival_-_Magnolia_Awards_in_June_2019.jpg", "tags": ["C-pop", "diễn viên", "nội tâm"],
    },
    {
        "name": "Lưu Vũ Ninh (Liu Yuning)",
        "origin": "Trung Quốc 🇨🇳", "job": "Ca sĩ (OST specialist)",
        "birthday": "17/04/1996", "height": "1m80", "weight": "68 kg",
        "blood_type": "A", "zodiac": "Bạch Dương ♈",
        "fav_color": "Xanh dương & Trắng", "fav_number": "4",
        "status": "Độc thân 💫",
        "hobbies": "Guitar, viết nhạc, đọc sách, nấu ăn",
        "top_works": "OST 'Till the End of the Moon', 'Love Between Fairy and Devil', nhiều OST hit",
        "awards": "Weibo Popular Singer Awards, Golden Eagle Music Awards",
        "intro": "Lưu Vũ Ninh sinh ngày 17/04/1996 — giọng hát trầm ấm đặc trưng chuyên hát OST cho các drama lớn. Nghe mà không biết tên là thiệt thòi lớn! Khuôn mặt thư sinh điềm tĩnh, kiểu đẹp nghệ sĩ nội tâm. OST 'Till the End of the Moon' viral khắp châu Á.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Liu_Yuning_%E5%88%98%E5%AE%87%E5%AE%81_COSMO_%E5%BA%86%E5%85%B8%E6%B4%BB%E5%8A%A8_1.jpg/400px-Liu_Yuning_%E5%88%98%E5%AE%87%E5%AE%81_COSMO_%E5%BA%86%E5%85%B8%E6%B4%BB%E5%8A%A8_1.jpg", "tags": ["C-pop", "OST", "giọng hát"],
    },
    {
        "name": "Hoắc Kiến Hoa (Wallace Huo)",
        "origin": "Đài Loan 🇹🇼", "job": "Diễn viên, ca sĩ",
        "birthday": "25/03/1979", "height": "1m82", "weight": "72 kg",
        "blood_type": "A", "zodiac": "Bạch Dương ♈",
        "fav_color": "Đen & Trắng & Nâu", "fav_number": "25",
        "status": "Đã kết hôn 💍",
        "hobbies": "Đánh trống (nhạc cụ), cưỡi ngựa, gym, thiên nhiên",
        "top_works": "'Hoa Thiên Cốt' (2015 — phá kỷ lục rating), 'Perfect Couple', 'Ruyi's Royal Love'",
        "awards": "Golden Bell Awards (TW), Weibo Drama Awards, Golden Eagle TV Festival",
        "intro": "Hoắc Kiến Hoa sinh ngày 25/03/1979, cao 1m82 — 'Hoa Thiên Cốt' năm 2015 là phim Trung Hoa rating cao nhất lịch sử thời điểm đó. Kiểu đẹp chín chắn phong trần sang trọng — đàn ông 40+ vẫn đỉnh như này là hiếm có!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Wallace_Huo_image_taken_in_November_2016.png/400px-Wallace_Huo_image_taken_in_November_2016.png", "tags": ["Đài Loan", "diễn viên", "cổ trang"],
    },
    {
        "name": "Eddie Peng (Bành Vu Yến)",
        "origin": "Đài Loan 🇹🇼", "job": "Diễn viên",
        "birthday": "24/03/1982", "height": "1m83", "weight": "80 kg",
        "blood_type": "O", "zodiac": "Bạch Dương ♈",
        "fav_color": "Đen & Đỏ", "fav_number": "8",
        "status": "Độc thân 💫",
        "hobbies": "Gym (tập rất nặng cho vai phim), boxing, marathon, bơi lội",
        "top_works": "'Unbeatable' (2013 — body 6-pack iconic), 'Rise of the Legend' (2014), 'Wu Kong' (2017)",
        "awards": "Hong Kong Film Awards đề cử, Golden Horse Awards đề cử",
        "intro": "Eddie Peng sinh ngày 24/03/1982, cao 1m83 — tập boxing và gym 6 tháng để đạt body 6-pack chuẩn võ sĩ cho phim 'Unbeatable', kết quả khiến cả internet ngừng thở. Không phải body diễn — là body thật sự. Định nghĩa của 'nỗ lực tạo nên hoàn hảo'!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Eddie_Peng_%28%E5%BD%AD%E4%BA%8E%E6%99%8F%29_in_October_2018.png/400px-Eddie_Peng_%28%E5%BD%AD%E4%BA%8E%E6%99%8F%29_in_October_2018.png", "tags": ["Đài Loan", "diễn viên", "6-pack 🔥"],
    },
    {
        "name": "Nicholas Tse (Tạ Đình Phong)",
        "origin": "Hồng Kông 🇭🇰", "job": "Diễn viên, ca sĩ, đầu bếp TV",
        "birthday": "26/08/1980", "height": "1m80", "weight": "72 kg",
        "blood_type": "A", "zodiac": "Xử Nữ ♍",
        "fav_color": "Đen & Trắng", "fav_number": "26",
        "status": "Độc thân 💫",
        "hobbies": "Nấu ăn chuyên nghiệp (show riêng), mô tô, gym, F1",
        "top_works": "Phim HK 'Young and Dangerous'; TV show 'Chef Nic' (nổi tiếng khắp châu Á); nhiều album",
        "awards": "HK Film Awards đề cử, Golden Horse đề cử, CCTV Food Show Awards",
        "intro": "Tạ Đình Phong sinh ngày 26/08/1980, cao 1m80 — từ ca sĩ idol đến diễn viên action đến đầu bếp TV chuyên nghiệp có show riêng! Ông nội là diễn viên huyền thoại Tạ Hiền. Tuổi 44 mà vẫn body đỉnh, phong thái hoàn hảo — lão mà không già!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/2017.2.13_%E5%86%B3%E6%88%98%E9%A3%9F%E7%A5%9E%E5%90%88%E8%82%A5%E8%B7%AF%E6%BC%94_%E8%B0%A2%E9%9C%86%E9%94%8B_%288%29.jpg/400px-2017.2.13_%E5%86%B3%E6%88%98%E9%A3%9F%E7%A5%9E%E5%90%88%E8%82%A5%E8%B7%AF%E6%BC%94_%E8%B0%A2%E9%9C%86%E9%94%8B_%288%29.jpg", "tags": ["HK cinema", "đầu bếp TV", "đa tài"],
    },
    {
        "name": "Lâm Phong (Raymond Lam)",
        "origin": "Hồng Kông 🇭🇰", "job": "Ca sĩ, diễn viên",
        "birthday": "08/12/1983", "height": "1m79", "weight": "70 kg",
        "blood_type": "O", "zodiac": "Nhân Mã ♐",
        "fav_color": "Xanh dương & Trắng", "fav_number": "8",
        "status": "Đã kết hôn 💍",
        "hobbies": "Guitar, gym, thể thao, thiên nhiên",
        "top_works": "TVB 'Beyond the Realm of Conscience' (2009), 'A Change of Heart', nhiều album Cantopop",
        "awards": "TVB Anniversary Awards (Nam diễn viên xuất sắc), ifpi HK Cantopop Awards",
        "intro": "Raymond Lam sinh ngày 08/12/1983, cao 1m79 — ngôi sao TVB và Cantopop quen thuộc với khán giả Việt thế hệ 8X-9X. Khuôn mặt điền trai kiểu trai lành HK, giọng hát ấm áp đặc trưng. Vẫn giữ được fan base trung thành đông đảo sau nhiều năm.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Raymond_Lam_Fung.jpg/400px-Raymond_Lam_Fung.jpg", "tags": ["HK cinema", "Cantopop", "TVB"],
    },
    {
        "name": "Aaron Yan (Viêm Á Luân)",
        "origin": "Đài Loan 🇹🇼", "job": "Ca sĩ, diễn viên (FAHRENHEIT)",
        "birthday": "23/11/1985", "height": "1m82", "weight": "72 kg",
        "blood_type": "O", "zodiac": "Nhân Mã ♐",
        "fav_color": "Xanh dương & Trắng", "fav_number": "23",
        "status": "Độc thân 💫",
        "hobbies": "Nhảy (chuyên nghiệp), guitar, thể thao",
        "top_works": "Fahrenheit, drama 'Just You' (2013), 'Fall in Love with Me' (2014)",
        "awards": "Golden Bell Awards đề cử, Asian Television Awards, Idol Drama Awards",
        "intro": "Aaron Yan sinh ngày 23/11/1985, cao 1m82 — thành viên Fahrenheit (idol group Đài Loan đình đám thập kỷ 2000-2010). Drama 'Just You' gây sốt khắp Đông Á. Dũng cảm công khai là thành viên cộng đồng LGBTQ+ — được đông đảo fan ủng hộ và tôn trọng!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/20210124_%E7%82%8E%E4%BA%9E%E7%B6%B8_%E6%91%A9%E7%99%BB%E5%8E%9F%E5%A7%8B%E4%BA%BA%E9%AB%98%E9%9B%84%E7%B0%BD%E5%94%B1%E6%9C%83.jpg/400px-20210124_%E7%82%8E%E4%BA%9E%E7%B6%B8_%E6%91%A9%E7%99%BB%E5%8E%9F%E5%A7%8B%E4%BA%BA%E9%AB%98%E9%9B%84%E7%B0%BD%E5%94%B1%E6%9C%83.jpg", "tags": ["Đài Loan", "FAHRENHEIT", "idol"],
    },
    {
        "name": "Lưu Dĩ Hào (Jasper Liu)",
        "origin": "Đài Loan 🇹🇼", "job": "Diễn viên, người mẫu",
        "birthday": "01/04/1988", "height": "1m86", "weight": "75 kg",
        "blood_type": "B", "zodiac": "Bạch Dương ♈",
        "fav_color": "Trắng & Xám", "fav_number": "1",
        "status": "Độc thân 💫",
        "hobbies": "Thể thao ngoài trời, mô tô, gym, thời trang",
        "top_works": "'Before We Get Married' (2019 — fan VN mê điên đảo), 'Dear Lemon Chicken'",
        "awards": "Golden Bell Awards đề cử, Asian Television Awards đề cử",
        "intro": "Lưu Dĩ Hào sinh ngày 01/04/1988, cao 1m86 — diễn viên và người mẫu Đài Loan với chiều cao lý tưởng. Khuôn mặt điền trai đàn ông trưởng thành, phong thái tự tin phóng khoáng. 'Before We Get Married' có lượng fan VN rất lớn. An toàn để thích!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Jasper_Liu_20200901.jpg", "tags": ["Đài Loan", "diễn viên", "người mẫu"],
    },
    {
        "name": "Đậu Kiêu (Shawn Dou)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên",
        "birthday": "21/02/1989", "height": "1m85", "weight": "75 kg",
        "blood_type": "A", "zodiac": "Song Ngư ♓",
        "fav_color": "Đen & Xanh dương đậm", "fav_number": "21",
        "status": "Độc thân 💫",
        "hobbies": "Guitar điện, mô tô, gym, nhạc rock",
        "top_works": "'Nothing Gold Can Stay', 'The Flame's Daughter', 'Nirvana in Fire' (vai phụ)",
        "awards": "Weibo Drama Awards, Golden Eagle TV Arts Festival, iQiyi Starlight Awards",
        "intro": "Đậu Kiêu sinh ngày 21/02/1989, cao 1m85 — diễn viên với phong thái 'bad boy nghệ sĩ' cực kỳ hấp dẫn. Mê mô tô và guitar điện — không phải mẫu idol an toàn thông thường. Body cao to rắn chắc. Bí ẩn đáng khám phá trong C-drama!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Shawn_Dou_at_Dior_event.png/400px-Shawn_Dou_at_Dior_event.png", "tags": ["C-pop", "diễn viên", "bad boy"],
    },
    {
        "name": "Hà Tuấn Lâm (He Junlin)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên, ca sĩ",
        "birthday": "07/07/1998", "height": "1m82", "weight": "67 kg",
        "blood_type": "O", "zodiac": "Cự Giải ♋",
        "fav_color": "Xanh lam & Trắng", "fav_number": "7",
        "status": "Độc thân 💫",
        "hobbies": "Nhảy, viết nhạc, photography, bóng rổ",
        "top_works": "'Day Day Up' (Hồ Nam TV), 'Nirvana in Fire II', 'Lost Track of Time'",
        "awards": "Mango TV Popular Star Awards, Weibo New Idol Awards",
        "intro": "Hà Tuấn Lâm sinh ngày 07/07/1998, cao 1m82 — idol trẻ đang lên với ngoại hình thư sinh điển trai. Chinh phục khán giả qua 'Day Day Up' với hài hước tự nhiên và vũ đạo ấn tượng. Đẹp kiểu clean và tươi sáng — cái tên đáng theo dõi!",
        "image_url": "", "tags": ["C-pop", "idol", "thư sinh"],
    },
    {
        "name": "Lương Gia Huy (Connor Leong)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên",
        "birthday": "19/07/1999", "height": "1m84", "weight": "70 kg",
        "blood_type": "AB", "zodiac": "Cự Giải ♋",
        "fav_color": "Trắng & Xanh dương nhạt", "fav_number": "19",
        "status": "Độc thân 💫",
        "hobbies": "Bơi lội, gym, xem phim nghệ thuật, nhạc indie",
        "top_works": "'A Little Thing Called First Love' (2019), 'You Are My Destiny' (2020)",
        "awards": "Weibo Drama Awards, iQiyi New Generation Awards",
        "intro": "Lương Gia Huy sinh ngày 19/07/1999, cao 1m84 — đẹp như 'idol Hàn Quốc bước vào phim Trung Quốc'. Khuôn mặt trắng trẻo tỷ lệ hoàn hảo, nụ cười ngây thơ. Body bơi lội cân đối. 'A Little Thing Called First Love' làm bùng nổ fandom!",
        "image_url": "", "tags": ["C-pop", "diễn viên", "thư sinh"],
    },
    {
        "name": "Từ Hải Kiều (Xu Haiqiao)",
        "origin": "Trung Quốc 🇨🇳", "job": "Diễn viên",
        "birthday": "25/02/1987", "height": "1m86", "weight": "78 kg",
        "blood_type": "A", "zodiac": "Song Ngư ♓",
        "fav_color": "Nâu đất & Đen", "fav_number": "6",
        "status": "Đã kết hôn 💍",
        "hobbies": "Cưỡi ngựa, kiếm thuật thật sự, gym, thư pháp",
        "top_works": "'The Story of Ming Lan' (2018 — rating cao), 'Word of Honor', 'Ancient Detective'",
        "awards": "Weibo Drama Awards, Golden Eagle TV Arts Festival, iQiyi Starlight Awards",
        "intro": "Từ Hải Kiều sinh ngày 25/02/1987, cao 1m86 — diễn viên cổ trang hàng đầu TQ. Cưỡi ngựa và kiếm thuật thật sự (không phải diễn), rất có ích khi đóng cổ trang. Khí chất đại nhân quân tử tự nhiên. Mẫu chồng trong tiểu thuyết ngôn tình đã bước ra đời thật!",
        "image_url": "", "tags": ["C-pop", "diễn viên", "cổ trang"],
    },

    # ── 🇯🇵 Nhật Bản ──────────────────────────────────────────────────────────
    {
        "name": "Kento Yamazaki",
        "origin": "Nhật Bản 🇯🇵", "job": "Diễn viên",
        "birthday": "07/09/1994", "height": "1m80", "weight": "68 kg",
        "blood_type": "B", "zodiac": "Xử Nữ ♍",
        "fav_color": "Đen & Trắng", "fav_number": "7",
        "status": "Độc thân 💫",
        "hobbies": "Bơi lội, gym, xem anime, chụp ảnh đường phố",
        "top_works": "Netflix 'Alice in Borderland' (2020/2022 — top Netflix toàn cầu), 'Death Note' (2016)",
        "awards": "Japan Academy Film Award đề cử, Hochi Film Award, Nikkan Sports Film Award",
        "intro": "Kento Yamazaki sinh ngày 07/09/1994, cao 1m80 — được yêu mến rộng rãi tại VN sau 'Alice in Borderland' trên Netflix. Biểu cảm cực kỳ sâu sắc, khiến khán giả toàn cầu phải tìm hiểu về anh. Body từ bơi lội cân đối đẹp. Xem Alice mà không fangirl Kento = bất khả thi!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Kingdom%2BSingapore%2BPremiere%2BPress%2BConference%2Bcaagvhp5Gwax.jpg/400px-Kingdom%2BSingapore%2BPremiere%2BPress%2BConference%2Bcaagvhp5Gwax.jpg", "tags": ["J-drama", "Netflix 🎬", "diễn viên"],
    },
    {
        "name": "Mackenyu (Maeda Mackenyu)",
        "origin": "Nhật Bản 🇯🇵", "job": "Diễn viên",
        "birthday": "16/06/1996", "height": "1m80", "weight": "75 kg",
        "blood_type": "O", "zodiac": "Song Tử ♊",
        "fav_color": "Đen & Xanh lá", "fav_number": "16",
        "status": "Độc thân 💫",
        "hobbies": "Võ thuật (judo, karate), gym (tập nặng), nhảy, đọc manga",
        "top_works": "Netflix 'One Piece' live action (vai Zoro — 2023 viral toàn cầu), 'Rurouni Kenshin'",
        "awards": "Japan Film Critics đề cử, Netflix Global Top 10 (#1 nhiều tuần — One Piece)",
        "intro": "Mackenyu sinh ngày 16/06/1996 — con trai diễn viên huyền thoại Sonny Chiba. Vai Zoro trong 'One Piece' Netflix 2023 chinh phục cả cộng đồng fan toàn cầu — body từ tập võ thuật thật sự rắn chắc và đẹp. Ngôi sao Nhật đang chinh phục Hollywood!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Mackenyu.png/400px-Mackenyu.png", "tags": ["J-drama", "One Piece 🗡️", "6-pack 🔥"],
    },
    {
        "name": "Takeru Satoh",
        "origin": "Nhật Bản 🇯🇵", "job": "Diễn viên",
        "birthday": "21/03/1989", "height": "1m75", "weight": "62 kg",
        "blood_type": "A", "zodiac": "Bạch Dương ♈",
        "fav_color": "Đỏ & Trắng", "fav_number": "21",
        "status": "Đã kết hôn 💍",
        "hobbies": "Kiếm thuật chuyên nghiệp (cho phim), gym, đọc sử",
        "top_works": "'Rurouni Kenshin' (series phim 2012-2021 — loạt phim action Nhật đỉnh nhất)",
        "awards": "Japan Academy Film Prize (đề cử nhiều lần), Blue Ribbon Awards, Hochi Film Award",
        "intro": "Takeru Satoh sinh ngày 21/03/1989 — huyền thoại điện ảnh Nhật với vai Himura Kenshin kéo dài gần 10 năm. Tập kiếm thuật thật sự — không phải stunt double. Khuôn mặt thanh tú tinh tế, diễn xuất sâu sắc. Ví dụ hoàn hảo về idol trưởng thành thành diễn viên thật sự!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Sato_Takeru_from_%22One_Night%22_at_Opening_Ceremony_of_the_Tokyo_International_Film_Festival_2019_%2849013876096%29.jpg/400px-Sato_Takeru_from_%22One_Night%22_at_Opening_Ceremony_of_the_Tokyo_International_Film_Festival_2019_%2849013876096%29.jpg", "tags": ["J-cinema", "diễn viên", "kiếm thuật"],
    },
    {
        "name": "Ryusei Yokohama",
        "origin": "Nhật Bản 🇯🇵", "job": "Diễn viên",
        "birthday": "20/12/1996", "height": "1m79", "weight": "67 kg",
        "blood_type": "O", "zodiac": "Nhân Mã ♐",
        "fav_color": "Xanh dương & Trắng", "fav_number": "20",
        "status": "Độc thân 💫",
        "hobbies": "Tennis, bơi lội, đọc sách, healthy lifestyle",
        "top_works": "'Anata no Bangō wa' (2019), 'Summer Time Rendering' (2022), Netflix projects",
        "awards": "Television Drama Academy Award đề cử, Nikkan Sports Film Awards",
        "intro": "Ryusei Yokohama sinh ngày 20/12/1996, cao 1m79 — gương mặt điển trai J-drama thế hệ mới. Từ drama lãng mạn đến thriller tâm lý đều xử lý tốt. Netflix đang chú ý anh cho dự án quốc tế. Mẫu bạn trai lý tưởng Nhật Bản — healthy, chăm chỉ, tử tế!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Ryusei_Yokohama_20190704.jpg/400px-Ryusei_Yokohama_20190704.jpg", "tags": ["J-drama", "diễn viên"],
    },
    {
        "name": "Taishi Nakagawa",
        "origin": "Nhật Bản 🇯🇵", "job": "Diễn viên",
        "birthday": "31/05/1995", "height": "1m77", "weight": "65 kg",
        "blood_type": "A", "zodiac": "Song Tử ♊",
        "fav_color": "Xanh lá & Nâu nhạt", "fav_number": "31",
        "status": "Độc thân 💫",
        "hobbies": "Guitar, kendo, đọc tiểu thuyết, nấu ăn",
        "top_works": "'Chihayafuru' (series phim 2016/2018/2019 — ăn khách), 'First Love'",
        "awards": "Japan Academy Film Prize đề cử, Eiga no Hi Award",
        "intro": "Taishi Nakagawa sinh ngày 31/05/1995, cao 1m77 — được biết đến qua 'Chihayafuru' với vai Arata mà fangirl Nhật/Việt mê không rứt. Khuôn mặt thanh tú, nụ cười ấm áp chân thành, chemistry với bạn diễn cực kỳ tự nhiên. Nam chính lãng mạn ai cũng muốn gặp!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Taishi_Nakagawa_IMG_4276-1a_20181228.jpg/400px-Taishi_Nakagawa_IMG_4276-1a_20181228.jpg", "tags": ["J-drama", "diễn viên"],
    },
]
