"""
handsome_guys.py - Danh sách 70+ trai đẹp châu Á, xoay vòng theo ngày
Cấu trúc tương tự quotes.py của ainews.
"""

GUYS = [
    # ── Việt Nam ──────────────────────────────────────────────────────────────
    {
        "name": "Sơn Tùng M-TP",
        "origin": "Việt Nam 🇻🇳",
        "job": "Ca sĩ, nhạc sĩ, producer",
        "intro": "Chàng trai sinh năm 1994 từ Thái Bình này đã làm mưa làm gió V-pop suốt hơn 10 năm. Cao 1m75, phong cách thời trang đỉnh cao, viết nhạc hay, hát hay — combo hoàn hảo khiến chị em mê mẩn. MV 'Có Chắc Yêu Là Đây' ra mắt là lập kỷ lục views, còn 'Making My Way' thì thầm kể chuyện trưởng thành đầy chất thơ. Nói chung, Tùng vừa là idol vừa là nguồn cảm hứng sống cho cả thế hệ.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/S%C6%A1n_T%C3%B9ng_M-TP_in_2019.jpg/440px-S%C6%A1n_T%C3%B9ng_M-TP_in_2019.jpg",
        "tags": ["V-pop", "ca sĩ", "producer"],
    },
    {
        "name": "Đen Vâu",
        "origin": "Việt Nam 🇻🇳",
        "job": "Rapper, nhạc sĩ",
        "intro": "Nguyễn Đức Cường — nghệ danh Đen Vâu — là rapper Hà Nội sinh năm 1993 với phong cách trữ tình độc nhất V-rap. Nhạc anh không cần flex tiền bạc hay chain vàng, chỉ cần kể chuyện đời thường bằng ngôn từ tinh tế là đủ khiến cả triệu người đồng cảm. 'Mang Tiền Về Cho Mẹ', 'Bài Này Chill Phết', 'Đi Về Nhà' — toàn là bài anthem thế hệ. Vibe của Đen = cà phê sáng + ánh nắng ban mai, ai cũng thích.",
        "image_url": "",
        "tags": ["rapper", "V-rap", "indie"],
    },
    {
        "name": "Isaac",
        "origin": "Việt Nam 🇻🇳",
        "job": "Ca sĩ, diễn viên",
        "intro": "Jun Phạm trong nhóm 365 ngày trước, rồi tách ra solo với nghệ danh Isaac và thành công vang dội. Sinh năm 1994, cao ráo, thư sinh, hát ballad ngọt như mật ong — 'Thằng Điên' hay 'Nồng Nàn Hơi Thở Em' đều là những bài khiến bao trái tim rung rinh. Còn diễn xuất trong phim thì khỏi nói, vai nào cũng đẹp trai hết phần người khác. Crush quốc dân chứ còn gì nữa!",
        "image_url": "",
        "tags": ["V-pop", "ca sĩ", "diễn viên"],
    },
    {
        "name": "Erik",
        "origin": "Việt Nam 🇻🇳",
        "job": "Ca sĩ",
        "intro": "Nguyễn Minh Anh — Erik — sinh năm 1997, xuất thân từ Quảng Ngãi nhưng tỏa sáng khắp cả nước bằng giọng hát cao vút và phong cách trẻ trung. 'Ghen' cùng MIN là bài hát viral toàn cầu, còn 'Nơi Này Có Anh' thì là bài tỏ tình được dùng nhiều nhất Việt Nam. Khuôn mặt bầu bĩnh dễ thương, style đẹp, năng lượng dồi dào — Erik kiểu như 'người anh trai quốc dân' ai cũng muốn có trong cuộc đời.",
        "image_url": "",
        "tags": ["V-pop", "ca sĩ"],
    },
    {
        "name": "SOOBIN Hoàng Sơn",
        "origin": "Việt Nam 🇻🇳",
        "job": "Ca sĩ, nhạc sĩ",
        "intro": "Sinh năm 1995, SOOBIN là mẫu người nghệ sĩ trưởng thành dần theo năm tháng — từ 'Em Của Ngày Hôm Qua' ngây thơ đến 'Tội Ác' đầy nội tâm, anh không ngừng tự vượt qua mình. Cao 1m80, gương mặt góc cạnh, phong thái điềm tĩnh và rất... 'nghệ'. Người ta mê SOOBIN không chỉ vì ngoại hình mà còn vì chiều sâu trong âm nhạc — nghe anh hát xong hay tự hỏi tại sao cuộc đời mình chưa có người như vậy.",
        "image_url": "",
        "tags": ["V-pop", "ca sĩ", "nhạc sĩ"],
    },
    {
        "name": "Anh Tú Atus",
        "origin": "Việt Nam 🇻🇳",
        "job": "Ca sĩ",
        "intro": "Nhắc đến giọng hát nội lực trong thế hệ trẻ V-pop, không thể không kể Anh Tú. Sinh năm 1999, đẹp trai kiểu thư sinh, giọng tenor ấm áp — mỗi lần lên sân khấu là một lần khán giả được nghe âm nhạc theo nghĩa đẹp nhất. Từng gây bão tại các gameshow, giờ đây Anh Tú đang xây dựng con đường âm nhạc riêng đầy chất cá nhân. Loại đẹp trai mà gặp ngoài đường chị em sẽ phải quay đầu nhìn lại.",
        "image_url": "",
        "tags": ["V-pop", "ca sĩ"],
    },
    {
        "name": "Negav",
        "origin": "Việt Nam 🇻🇳",
        "job": "Rapper",
        "intro": "Ngô Tuấn Kiệt sinh năm 2000 — rapper trẻ nhất thế hệ nhưng flow thì già dặn không kém ai. Khuôn mặt bụ bẫm dễ thương mà rap cứ 'bắn' liên thanh không ngừng, phong cách tươi trẻ xen lẫn nghiêm túc khi cần. 'Bắn Tim' hay những màn collab cùng anh em 16 Typh đều gây sốt cộng đồng. Gen Z chính hiệu, vừa có talent vừa biết viral — Negav đang là cái tên đáng chú ý nhất V-hip-hop lúc này.",
        "image_url": "",
        "tags": ["rapper", "V-rap", "Gen Z"],
    },
    {
        "name": "Tăng Duy Tân",
        "origin": "Việt Nam 🇻🇳",
        "job": "Ca sĩ",
        "intro": "Chàng trai Gia Lai sinh năm 1998 này đang khiến cả Việt Nam 'Không Thể Say' vì độ hot của mình. Với hit 'Không Thể Say' viral khắp mạng xã hội, Tăng Duy Tân chứng minh rằng âm nhạc dân gian đương đại hoàn toàn có thể chinh phục cả triệu trái tim. Điểm cộng thêm: anh đẹp theo kiểu trai miền cao — cao ráo, da ngăm khoẻ khoắn, nụ cười rạng rỡ. Đủ mọi tiêu chí để fangirl điên đảo.",
        "image_url": "",
        "tags": ["V-pop", "ca sĩ", "dân gian đương đại"],
    },
    {
        "name": "Jack",
        "origin": "Việt Nam 🇻🇳",
        "job": "Ca sĩ, rapper",
        "intro": "Nguyễn Tấn Đức sinh năm 1997, nổi lên với những ca khúc ballad sâu lắng sau thời gian hoạt động cùng K-ICM. 'Hoa Hải Đường', 'Bạc Phận', 'Muộn Rồi Mà Sao Còn' — toàn những bài hit triệu view đầy cảm xúc. Khuôn mặt điền trai, ánh mắt buồn man mác, chất giọng đặc trưng khó lẫn lộn. Jack là kiểu nam thần mà chị em vừa muốn bảo vệ vừa muốn được bảo vệ — mâu thuẫn nhưng đúng!",
        "image_url": "",
        "tags": ["V-pop", "ballad", "ca sĩ"],
    },
    {
        "name": "Quang Hùng MasterD",
        "origin": "Việt Nam 🇻🇳",
        "job": "Ca sĩ, diễn viên",
        "intro": "Sinh năm 2000, Quang Hùng MasterD là gương mặt Gen Z đang lên mạnh trong V-pop. Đẹp theo kiểu idol Hàn — trắng trẻo, cao ráo, tóc xịn — nhưng lại mang âm nhạc thuần Việt đầy tự hào. 'Tự Tình' hay những ca khúc kết hợp yếu tố truyền thống với âm nhạc hiện đại của anh nhận được nhiều lời khen từ khán giả khó tính nhất. Vừa đẹp vừa tài, combo này hiếm lắm!",
        "image_url": "",
        "tags": ["V-pop", "ca sĩ", "Gen Z"],
    },

    # ── Hàn Quốc — BTS ────────────────────────────────────────────────────────
    {
        "name": "V (Kim Taehyung)",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ, diễn viên (BTS)",
        "intro": "Sinh năm 1995, V của BTS là người đàn ông được tạp chí thế giới bình chọn đẹp trai nhất nhiều lần — không phải ngẫu nhiên đâu nhé! Khuôn mặt đối xứng hoàn hảo, giọng hát trầm ấm quyến rũ, phong cách thời trang avant-garde không ai bắt kịp. Solo album 'Layover' vừa ra là lọt ngay Billboard, còn loạt ảnh phim trường thì khiến internet phải tắt mạng vì... quá đẹp. Taehyung là định nghĩa sống động của 'đẹp trai không tả được'.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Kim_Tae-hyung_at_the_2023_Melon_Music_Awards_%28cropped%29.jpg/440px-Kim_Tae-hyung_at_the_2023_Melon_Music_Awards_%28cropped%29.jpg",
        "tags": ["K-pop", "BTS", "idol"],
    },
    {
        "name": "Jungkook",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ (BTS)",
        "intro": "Maknae vàng của BTS — sinh năm 1997, Jungkook được mệnh danh là 'Golden Maknae' vì tài năng toàn diện: hát, nhảy, rap, vẽ, chụp ảnh, tập gym... làm gì cũng giỏi. Đặc biệt, cơ thể sau khi xuất ngũ của anh ấy khiến cả internet... ngất xỉu đúng nghĩa đen. 'Seven' và 'Standing Next to You' là những hit solo cán mốc toàn cầu. Jungkook là crush quốc tế chứ không chỉ quốc dân nữa rồi!",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/230916_Jungkook_Shoot_1_%28cropped%29.jpg/440px-230916_Jungkook_Shoot_1_%28cropped%29.jpg",
        "tags": ["K-pop", "BTS", "idol"],
    },
    {
        "name": "Jimin",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ (BTS)",
        "intro": "Park Jimin sinh năm 1995 — nghệ sĩ có lẽ được yêu quý nhất BTS nhờ sự kết hợp hiếm có giữa ngoại hình thiên thần và tài năng vũ đạo đỉnh cao. 'Like Crazy' phá kỷ lục Billboard Hot 100 với nghệ sĩ Hàn Quốc, còn solo album 'FACE' là lời tự sự chân thật về hành trình trưởng thành. Jimin nhỏ người nhưng sân khấu rộng lớn — mỗi màn trình diễn đều là một tác phẩm nghệ thuật hoàn chỉnh.",
        "image_url": "",
        "tags": ["K-pop", "BTS", "idol"],
    },
    {
        "name": "Jin (Kim Seokjin)",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ (BTS)",
        "intro": "Jin sinh năm 1992 — thành viên lớn tuổi nhất BTS nhưng nhan sắc thì cứ như không có tuổi. Anh nổi tiếng với danh hiệu 'Worldwide Handsome' tự phong nhưng được cả thế giới đồng ý. Giọng tenor trong vắt, khiếu hài hước tự nhiên, và màn trở về sau nghĩa vụ quân sự được fan chào đón như ngày hội. 'The Astronaut' hay 'Super Tuna' đều cho thấy Jin là người đa năng theo cách riêng rất đáng yêu.",
        "image_url": "",
        "tags": ["K-pop", "BTS", "idol"],
    },

    # ── Hàn Quốc — EXO ────────────────────────────────────────────────────────
    {
        "name": "Baekhyun",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ (EXO)",
        "intro": "Byun Baekhyun sinh năm 1992 — vocal main của EXO và là nghệ sĩ solo cực kỳ thành công của SM Entertainment. Giọng hát thiên phú, nụ cười mắt híp ngây ngô, khả năng aegyo (dễ thương có chủ đích) hàng đầu K-pop — Baekhyun là mẫu oppa mà ai cũng muốn có làm người anh. Album solo 'City Lights', 'Delight', 'Bambi' đều là những tác phẩm âm nhạc đỉnh cao, cán mốc triệu bản. Xuất ngũ rồi là anh bùng cháy trở lại!",
        "image_url": "",
        "tags": ["K-pop", "EXO", "idol"],
    },
    {
        "name": "Lay (Zhang Yixing)",
        "origin": "Trung Quốc 🇨🇳 / EXO",
        "job": "Ca sĩ, diễn viên, vũ công (EXO)",
        "intro": "Sinh năm 1991, Lay là thành viên người Trung Quốc duy nhất còn hoạt động song song với EXO và solo tại thị trường đại lục. Đây là anh chàng mà nhảy đẹp như múa, hát hay như nghệ sĩ cổ điển, diễn xuất được chuyên gia khen ngợi — và khuôn mặt thì cứ như điêu khắc. Nổi tiếng với album 'LOSE CONTROL' và hình ảnh đồng quê thuần phác đáng yêu, Lay là cầu nối văn hóa Hàn-Trung cực thú vị.",
        "image_url": "",
        "tags": ["K-pop", "EXO", "C-pop"],
    },
    {
        "name": "Cha Eunwoo",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ (ASTRO), diễn viên",
        "intro": "Lee Dong-min — nghệ danh Cha Eunwoo — sinh năm 1997 và được mệnh danh là 'nam thần nhan sắc' của làng giải trí Hàn Quốc một cách... không thể tranh cãi. Khuôn mặt cực kỳ đối xứng, cao 1m83, body rắn chắc — nhìn vào là hiểu tại sao người ta gọi anh là 'Real Life Manhwa Character'. Đóng phim 'True Beauty', 'My ID is Gangnam Beauty', 'A Good Day to be a Dog' đều nhận phản hồi tích cực. Eunwoo là minh chứng trời có mắt.",
        "image_url": "",
        "tags": ["K-pop", "ASTRO", "diễn viên"],
    },
    {
        "name": "Felix (Lee Yongbok)",
        "origin": "Úc 🇦🇺 / Hàn Quốc 🇰🇷",
        "job": "Ca sĩ (Stray Kids)",
        "intro": "Felix sinh năm 2000, người Úc gốc Hàn trong Stray Kids — và là ví dụ hoàn hảo cho 'đẹp không cần ngủ thêm'. Làn da trắng muốt, tàn nhang tự nhiên siêu cute, giọng bass trầm đặc trưng không lẫn vào đâu được, vũ đạo đỉnh cao. Khi 'MIROH' hay 'God's Menu' bắt đầu phát là Felix đã chiếm spotlight rồi. Còn bên ngoài sân khấu, anh ấy nấu ăn ngon, yêu gia đình, và tử tế với fan — crush lý tưởng đó!",
        "image_url": "",
        "tags": ["K-pop", "Stray Kids", "idol"],
    },
    {
        "name": "Yeonjun",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ, vũ công (TXT)",
        "intro": "Choi Yeonjun sinh năm 1999 — center và dancer chính của TOMORROW X TOGETHER, cũng là một trong những vũ công xuất sắc nhất thế hệ idol hiện tại. Trước khi debut đã nổi tiếng vì... quá đẹp và quá tài, vượt qua audition Big Hit trong hàng nghìn thí sinh. 'Good Boy Gone Bad', 'Sugar Rush Ride' — Yeonjun luôn là người đầu tiên bạn nhìn thấy trong MV. Kiểu đẹp sắc sảo, lạnh lùng trên sân khấu nhưng lại rất vui tính ngoài đời.",
        "image_url": "",
        "tags": ["K-pop", "TXT", "idol"],
    },
    {
        "name": "Hyunjin",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ, họa sĩ (Stray Kids)",
        "intro": "Hwang Hyunjin sinh năm 2000 — visual chính của Stray Kids và là một trong những idol K-pop được hâm mộ nhất toàn cầu. Nhưng điều khiến Hyunjin khác biệt không chỉ là khuôn mặt như tranh vẽ mà còn là tài năng hội họa thực sự — tranh anh đấu giá từ thiện thu về hàng trăm triệu won. Múa đẹp, vẽ giỏi, visual đỉnh: Hyunjin là nghệ sĩ toàn diện theo nghĩa thật nhất.",
        "image_url": "",
        "tags": ["K-pop", "Stray Kids", "idol"],
    },
    {
        "name": "Mark Lee",
        "origin": "Canada 🇨🇦 / Hàn Quốc 🇰🇷",
        "job": "Ca sĩ, rapper (NCT)",
        "intro": "Mark Lee sinh năm 1999 — người Canada gốc Hàn, là thành viên của cả NCT 127, NCT Dream và SuperM cùng lúc vì... anh không cần ngủ như người thường. Người ta gọi Mark là 'human mood board' vì năng lượng dồi dào, tích cực không giới hạn. Rap nhanh, hát tốt, vũ đạo chuẩn, tiếng Anh-Hàn-Trung đều ổn — và luôn gây cười với những màn nói chuyện thật thà hết sức. Crush của cả SM Town!",
        "image_url": "",
        "tags": ["K-pop", "NCT", "rapper"],
    },

    # ── Trung Quốc / C-pop ────────────────────────────────────────────────────
    {
        "name": "Vương Nhất Bác (Wang Yibo)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Ca sĩ, diễn viên, vũ công, đua xe",
        "intro": "Sinh năm 1997, Vương Nhất Bác từng là thành viên nhóm UNIQ trước khi bùng nổ toàn châu Á với vai Lam Vong Cơ trong 'Trần Tình Lệnh'. Cao 1m82, vibe lạnh lùng ngầu ngầu nhưng thực ra rất nghịch ngợm và tình cảm — fan biết hết! Anh còn đua xe chuyên nghiệp, nhảy UNIQ-era đẹp không kém idol Hàn, và có khả năng... nhìn thẳng vào camera khiến người xem quên mất mình đang thở.",
        "image_url": "",
        "tags": ["C-pop", "diễn viên", "idol"],
    },
    {
        "name": "Tiêu Chiến (Xiao Zhan)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Ca sĩ, diễn viên",
        "intro": "Sinh năm 1991 tại Trùng Khánh, Tiêu Chiến là cái tên gây bão khắp châu Á sau vai Ngụy Vô Tiện trong 'Trần Tình Lệnh'. Ngoài đời, anh vẽ tranh đẹp, nấu ăn ngon, và có nụ cười tỏa nắng sáng bừng cả căn phòng. Phim 'Chiến Lang' và loạt dự án sau đó chứng minh anh không chỉ là idol nhất thời mà là diễn viên có thực lực. Cộng đồng fan Tiêu Chiến ở Việt Nam đông không kém gì fandom quốc nội!",
        "image_url": "",
        "tags": ["C-pop", "diễn viên", "idol"],
    },
    {
        "name": "Lâm Nhất (Lin Yi)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên",
        "intro": "Sinh năm 1996, Lâm Nhất nổi lên mạnh mẽ qua drama 'Put Your Head on My Shoulder' (Em Hãy Tựa Vào Vai Anh). Anh thuộc típ đẹp thư sinh nhẹ nhàng — cao ráo, trắng trẻo, ánh mắt hiền lành như học sinh ngoan — nhưng đóng phim thì cực kỳ cuốn hút. Các phim tiếp theo như 'You Are My Glory' đều có đề cử tại các giải thưởng uy tín. Lâm Nhất là lựa chọn hàng đầu khi fangirl cần một buổi tối 'binge drama' chữa lành.",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Vương Hạc Đệ (Wang Hedi)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên, ca sĩ",
        "intro": "Sinh năm 1998, Vương Hạc Đệ nổi bật với vai Trình Thiếu Dương trong 'Một Nụ Cười Vạn Năm' và gần đây là loạt drama ăn khách. Anh đẹp theo kiểu tươi sáng rực rỡ — nụ cười năng lượng cao, mái tóc bồng bềnh, phong cách thời trang trendy. Ngoài đóng phim, Vương Hạc Đệ còn hoạt động âm nhạc, chứng minh mình không chỉ dựa vào visual. Vibe của anh = muôn ánh mặt trời buổi sáng!",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Cung Tuấn (Gong Jun)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên, ca sĩ",
        "intro": "Sinh năm 1992, Cung Tuấn — hay còn gọi ân ái là 'Tuấn Tuấn' — nổi lên với vai Chu Bảo Thần trong 'Sơn Hà Lệnh' cặp cùng Trương Triết Hạn. Cao 1m86, khuôn mặt điền trai, nụ cười phúc hậu, phong thái điềm đạm — anh là mẫu 'người anh lớn' đáng tin cậy nhất màn ảnh. Ngoài diễn xuất, Cung Tuấn còn tham gia nhiều chương trình giải trí và mỗi lần xuất hiện đều khiến không khí sáng bừng.",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Lý Hiện (Li Xian)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên",
        "intro": "Sinh năm 1991, Lý Hiện trở thành hiện tượng toàn châu Á với vai Giang Thần Thành trong 'Go Ahead' (Cha Tôi, Anh Trai Tôi Và Anh) — drama gia đình khiến cả Đông Nam Á khóc hết nước mắt. Ngoài đời, anh là người điềm tĩnh, thích đọc sách, nấu ăn và chơi thể thao — mẫu người đàn ông bình dị mà lại cực kỳ hấp dẫn. Lý Hiện là bằng chứng rằng sự chín chắn và trưởng thành có sức hút riêng không kém gì visual lóa mắt.",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Dương Dương (Yang Yang)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên",
        "intro": "Sinh năm 1991, Dương Dương là tên tuổi lớn của màn ảnh Trung Quốc với hàng loạt vai diễn ấn tượng trong 'Love O2O', 'You Are My City and Fortress'. Cao 1m84, khuôn mặt sắc nét góc cạnh, ánh mắt đầy nội tâm — anh thuộc mẫu đẹp kiêu kỳ nhưng lại rất gần gũi khi lên sóng variety show. Dương Dương không cần cố tạo ra charisma vì charisma tự nhiên từ trong ra.",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "La Vân Hi (Luo Yunxi)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên, vũ công",
        "intro": "Sinh năm 1988, La Vân Hi xuất thân là vũ công chuyên nghiệp trước khi chuyển hướng diễn xuất — và kết quả là có một diễn viên vừa đẹp vừa diễn xuất sắc vừa di chuyển uyển chuyển như nghệ sĩ múa. Vai Hứa Minh Nhuệ trong 'Hương Mật Tựa Khói Sương' và nhiều drama tiếp theo đều chứng minh tài năng không phải may mắn. Lão già 'tinh thần' của C-drama vì vừa đẹp vừa nhiều kinh nghiệm.",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Ngô Lỗi (Wu Lei)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên",
        "intro": "Sinh năm 1999, Ngô Lỗi là thần đồng diễn xuất — anh đã đóng phim từ nhỏ và nay trở thành ngôi sao trẻ sáng giá nhất màn ảnh Trung Quốc. Vai Long Bảo trong 'Sư Thúc' hay các drama cổ trang đều nhận được sự yêu mến từ khán giả. Đặc biệt, Ngô Lỗi có kiểu đẹp 'hoa thần' — tinh tế, thanh tú, toát ra khí chất trưởng thành vượt tuổi. Gen Z chính gốc nhưng diễn như lão nghệ sĩ!",
        "image_url": "",
        "tags": ["C-pop", "diễn viên", "Gen Z"],
    },
    {
        "name": "Trần Phi Vũ (Chen Feiyu)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên, ca sĩ",
        "intro": "Sinh năm 1999, Trần Phi Vũ là con trai đạo diễn Trần Khải Ca nhưng đã tự mình gây dựng tên tuổi bằng tài năng thật sự. Từ vai Ji Yanxin trong 'Ever Night' đến các dự án điện ảnh hiện đại, anh liên tục chứng minh mình không hề sống dựa vào bóng cha. Ngoại hình thư sinh, cao ráo, phong thái nghệ thuật — Trần Phi Vũ là mẫu nam thần có chiều sâu cả bên trong lẫn bên ngoài.",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Nhiệm Gia Luân (Ren Jialun)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên",
        "intro": "Sinh năm 1986, Nhiệm Gia Luân là anh lớn của làng C-drama với hàng loạt vai đế vương, thần tiên, công tử đều toát ra uy quyền tự nhiên. 'The Wolf', 'Till the End of the Moon' đều là những tác phẩm để đời. Cao 1m85, khuôn mặt uy nghiêm mà lại có nụ cười ấm áp bất ngờ — Nhiệm Gia Luân kiểu như 'sếp lớn trong tiểu thuyết ngôn tình' bước ra ngoài đời thật.",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Chu Nhất Long (Zhu Yilong)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên",
        "intro": "Sinh năm 1988, Chu Nhất Long nổi tiếng khắp cộng đồng C-drama với tài năng diễn xuất đỉnh cao và khả năng nhập vai cực kỳ đa dạng. Từ vai thiện sang vai phản diện, từ cổ trang sang hiện đại — anh đều xử lý mượt mà. Drama 'Guardian' từng gây sốt cả cộng đồng. Ngoài đời, Chu Nhất Long trầm lắng, ít nói, thích đọc sách — vibe trí thức nội tâm khiến nhiều người mê mẩn.",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Hứa Khải (Xu Kai)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên, ca sĩ",
        "intro": "Sinh năm 1994, Hứa Khải nổi lên với vai Phó Tư Thâm trong 'Story of Yanxi Palace' và từ đó trở thành cái tên không thể bỏ qua của C-drama. Cao 1m87, khuôn mặt tinh anh, diễn xuất đa chiều — anh có thể vừa đóng vai phản diện lạnh lùng vừa đóng vai tình lang ngọt ngào mà đều thuyết phục. Năng lượng của Hứa Khải trên màn ảnh là loại 'khó cưỡng' nhất!",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },

    # ── Nhật Bản ──────────────────────────────────────────────────────────────
    {
        "name": "Kento Yamazaki",
        "origin": "Nhật Bản 🇯🇵",
        "job": "Diễn viên",
        "intro": "Sinh năm 1994, Kento Yamazaki là ngôi sao điện ảnh và truyền hình Nhật được yêu mến rộng rãi tại Việt Nam sau series 'Alice in Borderland' trên Netflix. Khuôn mặt sắc nét, ánh mắt sâu thẳm, body rắn chắc — Kento là mẫu nam thần Nhật thuần túy không lẫn vào đâu. Phong cách diễn xuất tự nhiên, cảm xúc chân thật, mỗi vai diễn đều để lại dấu ấn. Xem 'Alice in Borderland' mà không fangirl Kento là điều gần như bất khả thi!",
        "image_url": "",
        "tags": ["J-drama", "diễn viên", "Netflix"],
    },
    {
        "name": "Ryusei Yokohama",
        "origin": "Nhật Bản 🇯🇵",
        "job": "Diễn viên",
        "intro": "Sinh năm 1996, Ryusei Yokohama là gương mặt điển trai của J-drama thế hệ mới — cao ráo, đa năng, và có khả năng diễn xuất vượt trội so với tuổi. Từ drama lãng mạn đến thriller hành động, anh đều xử lý tốt. Phong cách ngoài đời giản dị, thích tập thể thao, ăn uống healthy — mẫu bạn trai lý tưởng theo tiêu chuẩn Nhật Bản. Netflix đang 'nhắm' anh cho nhiều dự án quốc tế — theo dõi ngay kẻo muộn!",
        "image_url": "",
        "tags": ["J-drama", "diễn viên"],
    },
    {
        "name": "Taishi Nakagawa",
        "origin": "Nhật Bản 🇯🇵",
        "job": "Diễn viên",
        "intro": "Sinh năm 1995, Taishi Nakagawa là cái tên nổi bật trong thế hệ diễn viên Nhật trẻ với hàng loạt vai diễn ấn tượng trong phim điện ảnh và J-drama. Khuôn mặt thanh tú, nụ cười ấm áp, phong thái nhẹ nhàng — anh là típ đẹp trai 'dễ chịu' khiến người xem muốn xem đi xem lại. Đặc biệt trong các vai lãng mạn, Taishi tạo ra chemistry cực kỳ tự nhiên với bạn diễn, khiến khán giả tin vào chuyện tình yêu trên màn ảnh.",
        "image_url": "",
        "tags": ["J-drama", "diễn viên"],
    },
    {
        "name": "Gordon Lam",
        "origin": "Hồng Kông 🇭🇰",
        "job": "Diễn viên",
        "intro": "Lâm Gia Đống sinh năm 1967 — diễn viên kỳ cựu Hồng Kông với sự nghiệp lừng lẫy trong điện ảnh Hong Kong và quốc tế. Vai diễn trong 'Infernal Affairs', 'Drug War', 'Burning' đều được giới chuyên môn đánh giá cao. Ông là mẫu đàn ông trưởng thành, phong trần, có chiều sâu — proof rằng đàn ông đẹp nhất khi có thực lực và kinh nghiệm sống. Classic charm không bao giờ lỗi thời!",
        "image_url": "",
        "tags": ["HK cinema", "diễn viên"],
    },

    # ── Thêm K-pop & C-pop ────────────────────────────────────────────────────
    {
        "name": "Wonwoo (Jeon Wonwoo)",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ, rapper (SEVENTEEN)",
        "intro": "Sinh năm 1996, Wonwoo của SEVENTEEN có phong thái lạnh lùng bí ẩn trên sân khấu nhưng lại cực kỳ funny và đáng yêu khi livestream cùng fan. Khuôn mặt góc cạnh sắc bén, mắt một mí hút hồn, giọng rap trầm đặc trưng — Wonwoo là định nghĩa của 'bias wrecker' trong K-pop. Ngoài ra anh còn là mọt sách, thích triết học và nghệ thuật — depth không chỉ ở visual!",
        "image_url": "",
        "tags": ["K-pop", "SEVENTEEN", "rapper"],
    },
    {
        "name": "Jay (Park Jongseong)",
        "origin": "Mỹ 🇺🇸 / Hàn Quốc 🇰🇷",
        "job": "Ca sĩ (ENHYPEN)",
        "intro": "Sinh năm 2002, Jay của ENHYPEN là mẫu idol Gen Z chuẩn mực: đẹp trai, nói được 4 thứ tiếng (Anh, Hàn, Nhật, Trung), tính cách thẳng thắn và hài hước không cần filter. Vibe của Jay = bad boy với trái tim tốt — ngầu trên sân khấu, nhưng hay bật cười toe toét ngoài đời. Solo project 'BÊTE NOIRE' khiến fandom phát cuồng. ENHYPEN đang là nhóm K-pop 4th gen được chú ý nhất — và Jay là lý do!",
        "image_url": "",
        "tags": ["K-pop", "ENHYPEN", "idol"],
    },
    {
        "name": "Jungwon (Yang Jungwon)",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ (ENHYPEN)",
        "intro": "Leader trẻ nhất thế hệ sinh năm 2004, Yang Jungwon của ENHYPEN mang vẻ đẹp thuần khiết mà vẫn cực kỳ charismatic trên sân khấu. Là người điều phối và lãnh đạo nhóm ở tuổi còn rất trẻ nhưng làm tốt đến mức fan gọi anh là 'leader quốc dân'. Khuôn mặt bầu bĩnh dễ thương, nụ cười lúm đồng tiền, ánh mắt kiên định — Jungwon là mẫu 'em trai hoàn hảo' mà ai cũng muốn trong cuộc đời.",
        "image_url": "",
        "tags": ["K-pop", "ENHYPEN", "idol"],
    },
    {
        "name": "Taeyong (Lee Taeyong)",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ, rapper (NCT)",
        "intro": "Sinh năm 1995, Taeyong là leader và center của NCT 127 — người được mệnh danh là 'visual số 1 SM Entertainment' nhiều năm liên tiếp. Khuôn mặt sắc sảo như tác phẩm điêu khắc, vũ đạo sharp và chính xác, rap nhanh mà vẫn rõ từng chữ. Ngoài ra Taeyong còn thiết kế thời trang, vẽ tranh, và cook — bộ tổng. 'Kick It', 'Cherry Bomb' — những bài Taeyong 'bắn' là fan mất hồn.",
        "image_url": "",
        "tags": ["K-pop", "NCT", "rapper"],
    },
    {
        "name": "Bạch Kính Đình (Bai Jingting)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên",
        "intro": "Sinh năm 1993, Bạch Kính Đình là gương mặt quen thuộc của C-drama với phong thái điềm đạm, chắc chắn và rất... đáng tin. Vai diễn trong 'Forever and Ever' hay 'Time Flies and You Are Here' đều chứng minh anh có khả năng diễn xuất cảm xúc tinh tế. Kiểu đẹp của Bạch Kính Đình không phải lóa mắt ngay từ đầu mà càng nhìn càng thấy đẹp — loại 'acquired taste' nhưng một khi đã thấy thì không bỏ được.",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Trương Tân Thành (Zhang Xincheng)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên, ca sĩ",
        "intro": "Sinh năm 1997, Trương Tân Thành là cái tên ngày càng nổi trong C-drama với phong thái trẻ trung, tinh nghịch. Đặc biệt được biết đến qua 'Meteor Garden' phiên bản 2018 và nhiều drama hiện đại khác. Nụ cười tươi sáng, năng lượng tích cực lan tỏa — Trương Tân Thành kiểu như mặt trời của set phim, ai cũng mến. Ngoài diễn xuất còn hát được, múa được — Gen Z toàn năng!",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Đặng Luân (Deng Lun)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên",
        "intro": "Sinh năm 1992, Đặng Luân từng là một trong những diễn viên hot nhất C-drama với vai Hà Cẩm Túc trong 'Ashes of Love' (Hương Mật Tựa Khói Sương). Khuôn mặt đàn ông nhưng có nét tinh tế, mắt sâu thể hiện cảm xúc rất tốt — mỗi lần khóc trên phim là 100% khán giả khóc theo. Đặng Luân là bằng chứng rằng tài năng diễn xuất thật sự là loại đẹp không bao giờ phai.",
        "image_url": "",
        "tags": ["C-pop", "diễn viên"],
    },
    {
        "name": "Tống Uy Long (Song Weilong)",
        "origin": "Trung Quốc 🇨🇳",
        "job": "Diễn viên, người mẫu",
        "intro": "Sinh năm 1999, Tống Uy Long là mẫu nam thần trẻ đang lên mạnh trong showbiz Trung Quốc và cộng đồng fangirl châu Á. Cao 1m87, khuôn mặt lạnh lùng mà ẩn chứa nét lãng mạn, phong thái người mẫu toát ra từng cử chỉ. Đóng phim ngày càng có chiều sâu, xuất hiện trong nhiều tạp chí thời trang lớn. Tống Uy Long đang trên đà trở thành biểu tượng tầm cỡ châu lục — bắt đầu fangirl từ bây giờ để không muộn!",
        "image_url": "",
        "tags": ["C-pop", "diễn viên", "người mẫu"],
    },

    # ── Thêm V-pop ────────────────────────────────────────────────────────────
    {
        "name": "Rhyder (Trần Minh Tú)",
        "origin": "Việt Nam 🇻🇳",
        "job": "Ca sĩ, nhạc sĩ",
        "intro": "Sinh năm 2000, Rhyder là hiện tượng V-pop với chất nhạc R&B-soul thuần túy hiếm gặp trong làng nhạc Việt. Anh viết nhạc, sản xuất và hát — tất cả đều ở mức đỉnh cao. 'Người Lạ Ơi' (collab với Karik) hay 'Ngủ Một Mình' đều là những bài khiến người nghe nghiện không rứt ra được. Khuôn mặt điền trai, style laid-back chill, năng lượng sáng tạo dồi dào — Rhyder là nghệ sĩ mà càng tìm hiểu càng mê.",
        "image_url": "",
        "tags": ["V-pop", "R&B", "ca sĩ"],
    },
    {
        "name": "Bray",
        "origin": "Việt Nam 🇻🇳",
        "job": "Rapper, nhạc sĩ",
        "intro": "Tên thật Nguyễn Gia Bảo, sinh năm 1998, Bray là rapper underground Việt đang dần ra ánh sáng mainstream nhờ chất nhạc thật và tự sự. Flow anh có cái gì đó rất 'street' nhưng không hề cổ lỗ — kết hợp trap, drill với cảm xúc cá nhân rất riêng. Phong cách thời trang streetwear chuẩn rapper, khuôn mặt cá tính, ánh mắt có thần — Bray là mẫu bad boy âm nhạc khiến chị em vừa tò mò vừa muốn biết thêm.",
        "image_url": "",
        "tags": ["rapper", "V-rap", "underground"],
    },
    {
        "name": "Nguyễn Trần Trung Quân",
        "origin": "Việt Nam 🇻🇳",
        "job": "Ca sĩ, diễn viên",
        "intro": "Sinh năm 1992, Trung Quân Idol — như fan vẫn gọi — là giọng ca ballad nội lực với những bài hát chạm đến trái tim sâu nhất. 'Không Phải Dạng Vừa Đâu', 'Vĩnh Thứ Nhau', 'Bao Giờ Lấy Chồng' đều là những anthem thế hệ. Ngoài âm nhạc, anh còn là người thẳng thắn, cởi mở và có quan điểm rõ ràng về cuộc sống — loại nghệ sĩ mà follow để được nghe nói những điều hay.",
        "image_url": "",
        "tags": ["V-pop", "ballad", "ca sĩ"],
    },
    {
        "name": "MCK (Trọng Hiếu / RPT MCK)",
        "origin": "Việt Nam 🇻🇳",
        "job": "Rapper, nhạc sĩ",
        "intro": "Nguyễn Trọng Hiếu sinh năm 1999, rap từ hồi nhỏ và giờ đây là một trong những rapper được tôn trọng nhất V-hip-hop. Flow đỉnh, lyrics thật, không cần flex giả — MCK chọn kể câu chuyện của mình và khiến người nghe đồng cảm sâu sắc. Bên cạnh âm nhạc, anh còn nổi tiếng vì... đẹp trai kiểu rapper hiếm có ở Việt Nam. Tóc tai style, phong cách riêng, vibe authentic — crush của cộng đồng hip-hop VN.",
        "image_url": "",
        "tags": ["rapper", "V-rap"],
    },

    # ── Thêm K-pop ────────────────────────────────────────────────────────────
    {
        "name": "Taehyun (Choi Taehyun)",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ (TXT)",
        "intro": "Sinh năm 2000, Taehyun của TXT là vocal main với giọng hát 'chất như nước cất' — cao vút, kỹ thuật tốt, biểu đạt cảm xúc sâu sắc. Nhưng điều khiến fandom trầm trồ là body rắn chắc của anh trong khi vẫn giữ được khuôn mặt baby cute — cái combo đối lập siêu hấp dẫn. Anh tập gym nghiêm túc, thẳng thắn trả lời fan, và không ngại thể hiện cá tính rõ ràng. Taehyun là 'chân ái' của rất nhiều fans TXT.",
        "image_url": "",
        "tags": ["K-pop", "TXT", "idol"],
    },
    {
        "name": "Xiumin (Kim Minseok)",
        "origin": "Hàn Quốc 🇰🇷",
        "job": "Ca sĩ (EXO)",
        "intro": "Kim Minseok sinh năm 1990 — thành viên lớn tuổi nhất EXO nhưng mặt mũi cứ mãi baby face khiến ai cũng ghen tị. Xuất ngũ về là anh lại tiếp tục khiến fan 'không thở được' bằng loạt ảnh visual đỉnh cao và màn comeback đầy năng lượng. Xiumin là minh chứng sống rằng người đàn ông sinh năm 1990 hoàn toàn có thể vẫn dễ thương hơn nhiều bạn trẻ Gen Z. Bí quyết? Chắc là ít stress và ngủ đủ giấc.",
        "image_url": "",
        "tags": ["K-pop", "EXO", "idol"],
    },
    {
        "name": "Huang Renjun",
        "origin": "Trung Quốc 🇨🇳 / NCT",
        "job": "Ca sĩ (NCT Dream)",
        "intro": "Sinh năm 2000, Huang Renjun là thành viên người Trung Quốc của NCT Dream — nhỏ người nhưng personality cực lớn. Anh nổi tiếng trong fandom vì thẳng thắn, có quan điểm riêng, không ngại phản bác khi ai nói sai về nhóm. Tranh anh vẽ xuất hiện trong triển lãm chuyên nghiệp, nghệ thuật không chỉ là hobby. Huang Renjun là kiểu người vừa cute vừa sharp — đừng nhầm với mẫu idol 'hiền lành, không ý kiến'!",
        "image_url": "",
        "tags": ["K-pop", "NCT", "idol"],
    },
]
